// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/fedutinova/smartheart/back-api/service"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockSubmissionService is an autogenerated mock type for the SubmissionService type
type MockSubmissionService struct {
	mock.Mock
}

type MockSubmissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubmissionService) EXPECT() *MockSubmissionService_Expecter {
	return &MockSubmissionService_Expecter{mock: &_m.Mock}
}

// SubmitEKG provides a mock function with given fields: ctx, userID, imageURL, params
func (_m *MockSubmissionService) SubmitEKG(ctx context.Context, userID uuid.UUID, imageURL string, params service.ECGParams) (*service.SubmittedJob, error) {
	ret := _m.Called(ctx, userID, imageURL, params)

	if len(ret) == 0 {
		panic("no return value specified for SubmitEKG")
	}

	var r0 *service.SubmittedJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, service.ECGParams) (*service.SubmittedJob, error)); ok {
		return rf(ctx, userID, imageURL, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, service.ECGParams) *service.SubmittedJob); ok {
		r0 = rf(ctx, userID, imageURL, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SubmittedJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, service.ECGParams) error); ok {
		r1 = rf(ctx, userID, imageURL, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubmissionService_SubmitEKG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitEKG'
type MockSubmissionService_SubmitEKG_Call struct {
	*mock.Call
}

// SubmitEKG is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - imageURL string
//   - params service.ECGParams
func (_e *MockSubmissionService_Expecter) SubmitEKG(ctx interface{}, userID interface{}, imageURL interface{}, params interface{}) *MockSubmissionService_SubmitEKG_Call {
	return &MockSubmissionService_SubmitEKG_Call{Call: _e.mock.On("SubmitEKG", ctx, userID, imageURL, params)}
}

func (_c *MockSubmissionService_SubmitEKG_Call) Run(run func(ctx context.Context, userID uuid.UUID, imageURL string, params service.ECGParams)) *MockSubmissionService_SubmitEKG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(service.ECGParams))
	})
	return _c
}

func (_c *MockSubmissionService_SubmitEKG_Call) Return(_a0 *service.SubmittedJob, _a1 error) *MockSubmissionService_SubmitEKG_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubmissionService_SubmitEKG_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, service.ECGParams) (*service.SubmittedJob, error)) *MockSubmissionService_SubmitEKG_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitEKGFile provides a mock function with given fields: ctx, userID, file, params
func (_m *MockSubmissionService) SubmitEKGFile(ctx context.Context, userID uuid.UUID, file service.UploadedFile, params service.ECGParams) (*service.SubmittedJob, error) {
	ret := _m.Called(ctx, userID, file, params)

	if len(ret) == 0 {
		panic("no return value specified for SubmitEKGFile")
	}

	var r0 *service.SubmittedJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, service.UploadedFile, service.ECGParams) (*service.SubmittedJob, error)); ok {
		return rf(ctx, userID, file, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, service.UploadedFile, service.ECGParams) *service.SubmittedJob); ok {
		r0 = rf(ctx, userID, file, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SubmittedJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, service.UploadedFile, service.ECGParams) error); ok {
		r1 = rf(ctx, userID, file, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubmissionService_SubmitEKGFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitEKGFile'
type MockSubmissionService_SubmitEKGFile_Call struct {
	*mock.Call
}

// SubmitEKGFile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - file service.UploadedFile
//   - params service.ECGParams
func (_e *MockSubmissionService_Expecter) SubmitEKGFile(ctx interface{}, userID interface{}, file interface{}, params interface{}) *MockSubmissionService_SubmitEKGFile_Call {
	return &MockSubmissionService_SubmitEKGFile_Call{Call: _e.mock.On("SubmitEKGFile", ctx, userID, file, params)}
}

func (_c *MockSubmissionService_SubmitEKGFile_Call) Run(run func(ctx context.Context, userID uuid.UUID, file service.UploadedFile, params service.ECGParams)) *MockSubmissionService_SubmitEKGFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(service.UploadedFile), args[3].(service.ECGParams))
	})
	return _c
}

func (_c *MockSubmissionService_SubmitEKGFile_Call) Return(_a0 *service.SubmittedJob, _a1 error) *MockSubmissionService_SubmitEKGFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubmissionService_SubmitEKGFile_Call) RunAndReturn(run func(context.Context, uuid.UUID, service.UploadedFile, service.ECGParams) (*service.SubmittedJob, error)) *MockSubmissionService_SubmitEKGFile_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitGPT provides a mock function with given fields: ctx, userID, textQuery, files
func (_m *MockSubmissionService) SubmitGPT(ctx context.Context, userID uuid.UUID, textQuery string, files []service.UploadedFile) (*service.GPTSubmitResult, error) {
	ret := _m.Called(ctx, userID, textQuery, files)

	if len(ret) == 0 {
		panic("no return value specified for SubmitGPT")
	}

	var r0 *service.GPTSubmitResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []service.UploadedFile) (*service.GPTSubmitResult, error)); ok {
		return rf(ctx, userID, textQuery, files)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []service.UploadedFile) *service.GPTSubmitResult); ok {
		r0 = rf(ctx, userID, textQuery, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.GPTSubmitResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, []service.UploadedFile) error); ok {
		r1 = rf(ctx, userID, textQuery, files)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubmissionService_SubmitGPT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitGPT'
type MockSubmissionService_SubmitGPT_Call struct {
	*mock.Call
}

// SubmitGPT is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - textQuery string
//   - files []service.UploadedFile
func (_e *MockSubmissionService_Expecter) SubmitGPT(ctx interface{}, userID interface{}, textQuery interface{}, files interface{}) *MockSubmissionService_SubmitGPT_Call {
	return &MockSubmissionService_SubmitGPT_Call{Call: _e.mock.On("SubmitGPT", ctx, userID, textQuery, files)}
}

func (_c *MockSubmissionService_SubmitGPT_Call) Run(run func(ctx context.Context, userID uuid.UUID, textQuery string, files []service.UploadedFile)) *MockSubmissionService_SubmitGPT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].([]service.UploadedFile))
	})
	return _c
}

func (_c *MockSubmissionService_SubmitGPT_Call) Return(_a0 *service.GPTSubmitResult, _a1 error) *MockSubmissionService_SubmitGPT_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubmissionService_SubmitGPT_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, []service.UploadedFile) (*service.GPTSubmitResult, error)) *MockSubmissionService_SubmitGPT_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubmissionService creates a new instance of MockSubmissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubmissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubmissionService {
	mock := &MockSubmissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
