// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/fedutinova/smartheart/back-api/auth"

	job "github.com/fedutinova/smartheart/back-api/job"

	mock "github.com/stretchr/testify/mock"

	models "github.com/fedutinova/smartheart/back-api/models"

	service "github.com/fedutinova/smartheart/back-api/service"

	uuid "github.com/google/uuid"
)

// MockRequestService is an autogenerated mock type for the RequestService type
type MockRequestService struct {
	mock.Mock
}

type MockRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestService) EXPECT() *MockRequestService_Expecter {
	return &MockRequestService_Expecter{mock: &_m.Mock}
}

// GetJobStatus provides a mock function with given fields: ctx, jobID, claims
func (_m *MockRequestService) GetJobStatus(ctx context.Context, jobID uuid.UUID, claims *auth.Claims) (*job.Job, error) {
	ret := _m.Called(ctx, jobID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatus")
	}

	var r0 *job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *auth.Claims) (*job.Job, error)); ok {
		return rf(ctx, jobID, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *auth.Claims) *job.Job); ok {
		r0 = rf(ctx, jobID, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *auth.Claims) error); ok {
		r1 = rf(ctx, jobID, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatus'
type MockRequestService_GetJobStatus_Call struct {
	*mock.Call
}

// GetJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID uuid.UUID
//   - claims *auth.Claims
func (_e *MockRequestService_Expecter) GetJobStatus(ctx interface{}, jobID interface{}, claims interface{}) *MockRequestService_GetJobStatus_Call {
	return &MockRequestService_GetJobStatus_Call{Call: _e.mock.On("GetJobStatus", ctx, jobID, claims)}
}

func (_c *MockRequestService_GetJobStatus_Call) Run(run func(ctx context.Context, jobID uuid.UUID, claims *auth.Claims)) *MockRequestService_GetJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*auth.Claims))
	})
	return _c
}

func (_c *MockRequestService_GetJobStatus_Call) Return(_a0 *job.Job, _a1 error) *MockRequestService_GetJobStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetJobStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, *auth.Claims) (*job.Job, error)) *MockRequestService_GetJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function with given fields: ctx, requestID, claims
func (_m *MockRequestService) GetRequest(ctx context.Context, requestID uuid.UUID, claims *auth.Claims) (*models.Request, error) {
	ret := _m.Called(ctx, requestID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *auth.Claims) (*models.Request, error)); ok {
		return rf(ctx, requestID, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *auth.Claims) *models.Request); ok {
		r0 = rf(ctx, requestID, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *auth.Claims) error); ok {
		r1 = rf(ctx, requestID, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type MockRequestService_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - claims *auth.Claims
func (_e *MockRequestService_Expecter) GetRequest(ctx interface{}, requestID interface{}, claims interface{}) *MockRequestService_GetRequest_Call {
	return &MockRequestService_GetRequest_Call{Call: _e.mock.On("GetRequest", ctx, requestID, claims)}
}

func (_c *MockRequestService_GetRequest_Call) Run(run func(ctx context.Context, requestID uuid.UUID, claims *auth.Claims)) *MockRequestService_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*auth.Claims))
	})
	return _c
}

func (_c *MockRequestService_GetRequest_Call) Return(_a0 *models.Request, _a1 error) *MockRequestService_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequest_Call) RunAndReturn(run func(context.Context, uuid.UUID, *auth.Claims) (*models.Request, error)) *MockRequestService_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRequests provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockRequestService) GetUserRequests(ctx context.Context, userID uuid.UUID, limit int, offset int) (*service.RequestPage, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRequests")
	}

	var r0 *service.RequestPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (*service.RequestPage, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) *service.RequestPage); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RequestPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetUserRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRequests'
type MockRequestService_GetUserRequests_Call struct {
	*mock.Call
}

// GetUserRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockRequestService_Expecter) GetUserRequests(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockRequestService_GetUserRequests_Call {
	return &MockRequestService_GetUserRequests_Call{Call: _e.mock.On("GetUserRequests", ctx, userID, limit, offset)}
}

func (_c *MockRequestService_GetUserRequests_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockRequestService_GetUserRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRequestService_GetUserRequests_Call) Return(_a0 *service.RequestPage, _a1 error) *MockRequestService_GetUserRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetUserRequests_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) (*service.RequestPage, error)) *MockRequestService_GetUserRequests_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestService creates a new instance of MockRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestService {
	mock := &MockRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
