// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, oldPassword, newPassword
func (_m *MockPasswordService) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) error {
	ret := _m.Called(ctx, userID, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, userID, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockPasswordService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - oldPassword string
//   - newPassword string
func (_e *MockPasswordService_Expecter) ChangePassword(ctx interface{}, userID interface{}, oldPassword interface{}, newPassword interface{}) *MockPasswordService_ChangePassword_Call {
	return &MockPasswordService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, oldPassword, newPassword)}
}

func (_c *MockPasswordService_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string)) *MockPasswordService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPasswordService_ChangePassword_Call) Return(_a0 error) *MockPasswordService_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordService_ChangePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *MockPasswordService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmReset provides a mock function with given fields: ctx, token, newPassword
func (_m *MockPasswordService) ConfirmReset(ctx context.Context, token string, newPassword string) error {
	ret := _m.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordService_ConfirmReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmReset'
type MockPasswordService_ConfirmReset_Call struct {
	*mock.Call
}

// ConfirmReset is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockPasswordService_Expecter) ConfirmReset(ctx interface{}, token interface{}, newPassword interface{}) *MockPasswordService_ConfirmReset_Call {
	return &MockPasswordService_ConfirmReset_Call{Call: _e.mock.On("ConfirmReset", ctx, token, newPassword)}
}

func (_c *MockPasswordService_ConfirmReset_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockPasswordService_ConfirmReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPasswordService_ConfirmReset_Call) Return(_a0 error) *MockPasswordService_ConfirmReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordService_ConfirmReset_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPasswordService_ConfirmReset_Call {
	_c.Call.Return(run)
	return _c
}

// RequestReset provides a mock function with given fields: ctx, email
func (_m *MockPasswordService) RequestReset(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordService_RequestReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestReset'
type MockPasswordService_RequestReset_Call struct {
	*mock.Call
}

// RequestReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockPasswordService_Expecter) RequestReset(ctx interface{}, email interface{}) *MockPasswordService_RequestReset_Call {
	return &MockPasswordService_RequestReset_Call{Call: _e.mock.On("RequestReset", ctx, email)}
}

func (_c *MockPasswordService_RequestReset_Call) Run(run func(ctx context.Context, email string)) *MockPasswordService_RequestReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordService_RequestReset_Call) Return(_a0 error) *MockPasswordService_RequestReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordService_RequestReset_Call) RunAndReturn(run func(context.Context, string) error) *MockPasswordService_RequestReset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
