// Code generated manually to match mockery v2.52.3 style.

package mocks

import (
	context "context"

	service "github.com/fedutinova/smartheart/back-api/service"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, userID, analysesCount
func (_m *MockPaymentService) CreatePayment(ctx context.Context, userID uuid.UUID, analysesCount int) (*service.PaymentResult, error) {
	ret := _m.Called(ctx, userID, analysesCount)
	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}
	var r0 *service.PaymentResult
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *service.PaymentResult); ok {
		r0 = rf(ctx, userID, analysesCount)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*service.PaymentResult)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, analysesCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HandleWebhook provides a mock function with given fields: ctx, body
func (_m *MockPaymentService) HandleWebhook(ctx context.Context, body []byte) error {
	ret := _m.Called(ctx, body)
	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GetQuotaInfo provides a mock function with given fields: ctx, userID
func (_m *MockPaymentService) GetQuotaInfo(ctx context.Context, userID uuid.UUID) (*service.QuotaInfo, error) {
	ret := _m.Called(ctx, userID)
	if len(ret) == 0 {
		panic("no return value specified for GetQuotaInfo")
	}
	var r0 *service.QuotaInfo
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.QuotaInfo); ok {
		r0 = rf(ctx, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*service.QuotaInfo)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewMockPaymentService creates a new instance of MockPaymentService.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	m := &MockPaymentService{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
