// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockECGChatService is an autogenerated mock type for the ECGChatService type
type MockECGChatService struct {
	mock.Mock
}

type MockECGChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockECGChatService) EXPECT() *MockECGChatService_Expecter {
	return &MockECGChatService_Expecter{mock: &_m.Mock}
}

// GetMessages provides a mock function with given fields: ctx, requestID, userID
func (_m *MockECGChatService) GetMessages(ctx context.Context, requestID uuid.UUID, userID uuid.UUID) ([]models.ECGChatMessage, error) {
	ret := _m.Called(ctx, requestID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []models.ECGChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.ECGChatMessage, error)); ok {
		return rf(ctx, requestID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.ECGChatMessage); ok {
		r0 = rf(ctx, requestID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ECGChatMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockECGChatService_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockECGChatService_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - userID uuid.UUID
func (_e *MockECGChatService_Expecter) GetMessages(ctx interface{}, requestID interface{}, userID interface{}) *MockECGChatService_GetMessages_Call {
	return &MockECGChatService_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, requestID, userID)}
}

func (_c *MockECGChatService_GetMessages_Call) Run(run func(ctx context.Context, requestID uuid.UUID, userID uuid.UUID)) *MockECGChatService_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockECGChatService_GetMessages_Call) Return(_a0 []models.ECGChatMessage, _a1 error) *MockECGChatService_GetMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockECGChatService_GetMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.ECGChatMessage, error)) *MockECGChatService_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, requestID, userID, content
func (_m *MockECGChatService) SendMessage(ctx context.Context, requestID uuid.UUID, userID uuid.UUID, content string) (*models.ECGChatMessage, error) {
	ret := _m.Called(ctx, requestID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *models.ECGChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*models.ECGChatMessage, error)); ok {
		return rf(ctx, requestID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *models.ECGChatMessage); ok {
		r0 = rf(ctx, requestID, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ECGChatMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, requestID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockECGChatService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockECGChatService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - userID uuid.UUID
//   - content string
func (_e *MockECGChatService_Expecter) SendMessage(ctx interface{}, requestID interface{}, userID interface{}, content interface{}) *MockECGChatService_SendMessage_Call {
	return &MockECGChatService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, requestID, userID, content)}
}

func (_c *MockECGChatService_SendMessage_Call) Run(run func(ctx context.Context, requestID uuid.UUID, userID uuid.UUID, content string)) *MockECGChatService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockECGChatService_SendMessage_Call) Return(_a0 *models.ECGChatMessage, _a1 error) *MockECGChatService_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockECGChatService_SendMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*models.ECGChatMessage, error)) *MockECGChatService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockECGChatService creates a new instance of MockECGChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockECGChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockECGChatService {
	mock := &MockECGChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
