// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/fedutinova/smartheart/back-api/service"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: ctx, userID, analysesCount
func (_m *MockPaymentService) CreatePayment(ctx context.Context, userID uuid.UUID, analysesCount int) (*service.PaymentResult, error) {
	ret := _m.Called(ctx, userID, analysesCount)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *service.PaymentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*service.PaymentResult, error)); ok {
		return rf(ctx, userID, analysesCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *service.PaymentResult); ok {
		r0 = rf(ctx, userID, analysesCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PaymentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, analysesCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentService_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockPaymentService_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - analysesCount int
func (_e *MockPaymentService_Expecter) CreatePayment(ctx interface{}, userID interface{}, analysesCount interface{}) *MockPaymentService_CreatePayment_Call {
	return &MockPaymentService_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, userID, analysesCount)}
}

func (_c *MockPaymentService_CreatePayment_Call) Run(run func(ctx context.Context, userID uuid.UUID, analysesCount int)) *MockPaymentService_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentService_CreatePayment_Call) Return(_a0 *service.PaymentResult, _a1 error) *MockPaymentService_CreatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentService_CreatePayment_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (*service.PaymentResult, error)) *MockPaymentService_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubscription provides a mock function with given fields: ctx, userID
func (_m *MockPaymentService) CreateSubscription(ctx context.Context, userID uuid.UUID) (*service.PaymentResult, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 *service.PaymentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*service.PaymentResult, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.PaymentResult); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PaymentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentService_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MockPaymentService_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPaymentService_Expecter) CreateSubscription(ctx interface{}, userID interface{}) *MockPaymentService_CreateSubscription_Call {
	return &MockPaymentService_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, userID)}
}

func (_c *MockPaymentService_CreateSubscription_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPaymentService_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentService_CreateSubscription_Call) Return(_a0 *service.PaymentResult, _a1 error) *MockPaymentService_CreateSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentService_CreateSubscription_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*service.PaymentResult, error)) *MockPaymentService_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaInfo provides a mock function with given fields: ctx, userID
func (_m *MockPaymentService) GetQuotaInfo(ctx context.Context, userID uuid.UUID) (*service.QuotaInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaInfo")
	}

	var r0 *service.QuotaInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*service.QuotaInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.QuotaInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.QuotaInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentService_GetQuotaInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaInfo'
type MockPaymentService_GetQuotaInfo_Call struct {
	*mock.Call
}

// GetQuotaInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPaymentService_Expecter) GetQuotaInfo(ctx interface{}, userID interface{}) *MockPaymentService_GetQuotaInfo_Call {
	return &MockPaymentService_GetQuotaInfo_Call{Call: _e.mock.On("GetQuotaInfo", ctx, userID)}
}

func (_c *MockPaymentService_GetQuotaInfo_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPaymentService_GetQuotaInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentService_GetQuotaInfo_Call) Return(_a0 *service.QuotaInfo, _a1 error) *MockPaymentService_GetQuotaInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentService_GetQuotaInfo_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*service.QuotaInfo, error)) *MockPaymentService_GetQuotaInfo_Call {
	_c.Call.Return(run)
	return _c
}

// HandleWebhook provides a mock function with given fields: ctx, body
func (_m *MockPaymentService) HandleWebhook(ctx context.Context, body []byte) error {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentService_HandleWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebhook'
type MockPaymentService_HandleWebhook_Call struct {
	*mock.Call
}

// HandleWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
func (_e *MockPaymentService_Expecter) HandleWebhook(ctx interface{}, body interface{}) *MockPaymentService_HandleWebhook_Call {
	return &MockPaymentService_HandleWebhook_Call{Call: _e.mock.On("HandleWebhook", ctx, body)}
}

func (_c *MockPaymentService_HandleWebhook_Call) Run(run func(ctx context.Context, body []byte)) *MockPaymentService_HandleWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockPaymentService_HandleWebhook_Call) Return(_a0 error) *MockPaymentService_HandleWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentService_HandleWebhook_Call) RunAndReturn(run func(context.Context, []byte) error) *MockPaymentService_HandleWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
