// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	cv "github.com/fedutinova/smartheart/back-api/cv"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Health provides a mock function with given fields: ctx
func (_m *MockClient) Health(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockClient_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Health(ctx interface{}) *MockClient_Health_Call {
	return &MockClient_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockClient_Health_Call) Run(run func(ctx context.Context)) *MockClient_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Health_Call) Return(_a0 error) *MockClient_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Health_Call) RunAndReturn(run func(context.Context) error) *MockClient_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Predict provides a mock function with given fields: ctx, imageBytes, contentType, filename, layoutLabel, preprocessName
func (_m *MockClient) Predict(ctx context.Context, imageBytes []byte, contentType string, filename string, layoutLabel string, preprocessName string) (*cv.RhythmPrediction, error) {
	ret := _m.Called(ctx, imageBytes, contentType, filename, layoutLabel, preprocessName)

	if len(ret) == 0 {
		panic("no return value specified for Predict")
	}

	var r0 *cv.RhythmPrediction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, string) (*cv.RhythmPrediction, error)); ok {
		return rf(ctx, imageBytes, contentType, filename, layoutLabel, preprocessName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, string) *cv.RhythmPrediction); ok {
		r0 = rf(ctx, imageBytes, contentType, filename, layoutLabel, preprocessName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cv.RhythmPrediction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string, string, string) error); ok {
		r1 = rf(ctx, imageBytes, contentType, filename, layoutLabel, preprocessName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Predict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Predict'
type MockClient_Predict_Call struct {
	*mock.Call
}

// Predict is a helper method to define mock.On call
//   - ctx context.Context
//   - imageBytes []byte
//   - contentType string
//   - filename string
//   - layoutLabel string
//   - preprocessName string
func (_e *MockClient_Expecter) Predict(ctx interface{}, imageBytes interface{}, contentType interface{}, filename interface{}, layoutLabel interface{}, preprocessName interface{}) *MockClient_Predict_Call {
	return &MockClient_Predict_Call{Call: _e.mock.On("Predict", ctx, imageBytes, contentType, filename, layoutLabel, preprocessName)}
}

func (_c *MockClient_Predict_Call) Run(run func(ctx context.Context, imageBytes []byte, contentType string, filename string, layoutLabel string, preprocessName string)) *MockClient_Predict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockClient_Predict_Call) Return(_a0 *cv.RhythmPrediction, _a1 error) *MockClient_Predict_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Predict_Call) RunAndReturn(run func(context.Context, []byte, string, string, string, string) (*cv.RhythmPrediction, error)) *MockClient_Predict_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
