// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRAGFeedbackRepo is an autogenerated mock type for the RAGFeedbackRepo type
type MockRAGFeedbackRepo struct {
	mock.Mock
}

type MockRAGFeedbackRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRAGFeedbackRepo) EXPECT() *MockRAGFeedbackRepo_Expecter {
	return &MockRAGFeedbackRepo_Expecter{mock: &_m.Mock}
}

// CreateRAGFeedback provides a mock function with given fields: ctx, feedback
func (_m *MockRAGFeedbackRepo) CreateRAGFeedback(ctx context.Context, feedback *models.RAGFeedback) error {
	ret := _m.Called(ctx, feedback)

	if len(ret) == 0 {
		panic("no return value specified for CreateRAGFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RAGFeedback) error); ok {
		r0 = rf(ctx, feedback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRAGFeedbackRepo_CreateRAGFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRAGFeedback'
type MockRAGFeedbackRepo_CreateRAGFeedback_Call struct {
	*mock.Call
}

// CreateRAGFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - feedback *models.RAGFeedback
func (_e *MockRAGFeedbackRepo_Expecter) CreateRAGFeedback(ctx interface{}, feedback interface{}) *MockRAGFeedbackRepo_CreateRAGFeedback_Call {
	return &MockRAGFeedbackRepo_CreateRAGFeedback_Call{Call: _e.mock.On("CreateRAGFeedback", ctx, feedback)}
}

func (_c *MockRAGFeedbackRepo_CreateRAGFeedback_Call) Run(run func(ctx context.Context, feedback *models.RAGFeedback)) *MockRAGFeedbackRepo_CreateRAGFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RAGFeedback))
	})
	return _c
}

func (_c *MockRAGFeedbackRepo_CreateRAGFeedback_Call) Return(_a0 error) *MockRAGFeedbackRepo_CreateRAGFeedback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRAGFeedbackRepo_CreateRAGFeedback_Call) RunAndReturn(run func(context.Context, *models.RAGFeedback) error) *MockRAGFeedbackRepo_CreateRAGFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRAGFeedbackRepo creates a new instance of MockRAGFeedbackRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRAGFeedbackRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRAGFeedbackRepo {
	mock := &MockRAGFeedbackRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
