// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQuotaRepo is an autogenerated mock type for the QuotaRepo type
type MockQuotaRepo struct {
	mock.Mock
}

type MockQuotaRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaRepo) EXPECT() *MockQuotaRepo_Expecter {
	return &MockQuotaRepo_Expecter{mock: &_m.Mock}
}

// DecrementDailyUsage provides a mock function with given fields: ctx, userID
func (_m *MockQuotaRepo) DecrementDailyUsage(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementDailyUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuotaRepo_DecrementDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementDailyUsage'
type MockQuotaRepo_DecrementDailyUsage_Call struct {
	*mock.Call
}

// DecrementDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockQuotaRepo_Expecter) DecrementDailyUsage(ctx interface{}, userID interface{}) *MockQuotaRepo_DecrementDailyUsage_Call {
	return &MockQuotaRepo_DecrementDailyUsage_Call{Call: _e.mock.On("DecrementDailyUsage", ctx, userID)}
}

func (_c *MockQuotaRepo_DecrementDailyUsage_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockQuotaRepo_DecrementDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuotaRepo_DecrementDailyUsage_Call) Return(_a0 error) *MockQuotaRepo_DecrementDailyUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuotaRepo_DecrementDailyUsage_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuotaRepo_DecrementDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyUsage provides a mock function with given fields: ctx, userID
func (_m *MockQuotaRepo) GetDailyUsage(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyUsage")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaRepo_GetDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyUsage'
type MockQuotaRepo_GetDailyUsage_Call struct {
	*mock.Call
}

// GetDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockQuotaRepo_Expecter) GetDailyUsage(ctx interface{}, userID interface{}) *MockQuotaRepo_GetDailyUsage_Call {
	return &MockQuotaRepo_GetDailyUsage_Call{Call: _e.mock.On("GetDailyUsage", ctx, userID)}
}

func (_c *MockQuotaRepo_GetDailyUsage_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockQuotaRepo_GetDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuotaRepo_GetDailyUsage_Call) Return(_a0 int, _a1 error) *MockQuotaRepo_GetDailyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaRepo_GetDailyUsage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockQuotaRepo_GetDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementDailyUsage provides a mock function with given fields: ctx, userID
func (_m *MockQuotaRepo) IncrementDailyUsage(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementDailyUsage")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaRepo_IncrementDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementDailyUsage'
type MockQuotaRepo_IncrementDailyUsage_Call struct {
	*mock.Call
}

// IncrementDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockQuotaRepo_Expecter) IncrementDailyUsage(ctx interface{}, userID interface{}) *MockQuotaRepo_IncrementDailyUsage_Call {
	return &MockQuotaRepo_IncrementDailyUsage_Call{Call: _e.mock.On("IncrementDailyUsage", ctx, userID)}
}

func (_c *MockQuotaRepo_IncrementDailyUsage_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockQuotaRepo_IncrementDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuotaRepo_IncrementDailyUsage_Call) Return(_a0 int, _a1 error) *MockQuotaRepo_IncrementDailyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaRepo_IncrementDailyUsage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockQuotaRepo_IncrementDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaRepo creates a new instance of MockQuotaRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaRepo {
	mock := &MockQuotaRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
