// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenRepo is an autogenerated mock type for the TokenRepo type
type MockTokenRepo struct {
	mock.Mock
}

type MockTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepo) EXPECT() *MockTokenRepo_Expecter {
	return &MockTokenRepo_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockTokenRepo) CreateRefreshToken(ctx context.Context, token *models.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepo_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockTokenRepo_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.RefreshToken
func (_e *MockTokenRepo_Expecter) CreateRefreshToken(ctx interface{}, token interface{}) *MockTokenRepo_CreateRefreshToken_Call {
	return &MockTokenRepo_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, token)}
}

func (_c *MockTokenRepo_CreateRefreshToken_Call) Run(run func(ctx context.Context, token *models.RefreshToken)) *MockTokenRepo_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RefreshToken))
	})
	return _c
}

func (_c *MockTokenRepo_CreateRefreshToken_Call) Return(_a0 error) *MockTokenRepo_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepo_CreateRefreshToken_Call) RunAndReturn(run func(context.Context, *models.RefreshToken) error) *MockTokenRepo_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepo) GetRefreshToken(ctx context.Context, tokenHash string) (*models.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepo_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockTokenRepo_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepo_Expecter) GetRefreshToken(ctx interface{}, tokenHash interface{}) *MockTokenRepo_GetRefreshToken_Call {
	return &MockTokenRepo_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepo_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepo_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepo_GetRefreshToken_Call) Return(_a0 *models.RefreshToken, _a1 error) *MockTokenRepo_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepo_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*models.RefreshToken, error)) *MockTokenRepo_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevokedRefreshTokenOwner provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepo) GetRevokedRefreshTokenOwner(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRevokedRefreshTokenOwner")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepo_GetRevokedRefreshTokenOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevokedRefreshTokenOwner'
type MockTokenRepo_GetRevokedRefreshTokenOwner_Call struct {
	*mock.Call
}

// GetRevokedRefreshTokenOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepo_Expecter) GetRevokedRefreshTokenOwner(ctx interface{}, tokenHash interface{}) *MockTokenRepo_GetRevokedRefreshTokenOwner_Call {
	return &MockTokenRepo_GetRevokedRefreshTokenOwner_Call{Call: _e.mock.On("GetRevokedRefreshTokenOwner", ctx, tokenHash)}
}

func (_c *MockTokenRepo_GetRevokedRefreshTokenOwner_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepo_GetRevokedRefreshTokenOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepo_GetRevokedRefreshTokenOwner_Call) Return(_a0 uuid.UUID, _a1 error) *MockTokenRepo_GetRevokedRefreshTokenOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepo_GetRevokedRefreshTokenOwner_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *MockTokenRepo_GetRevokedRefreshTokenOwner_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserRefreshTokens provides a mock function with given fields: ctx, userID
func (_m *MockTokenRepo) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepo_RevokeAllUserRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserRefreshTokens'
type MockTokenRepo_RevokeAllUserRefreshTokens_Call struct {
	*mock.Call
}

// RevokeAllUserRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenRepo_Expecter) RevokeAllUserRefreshTokens(ctx interface{}, userID interface{}) *MockTokenRepo_RevokeAllUserRefreshTokens_Call {
	return &MockTokenRepo_RevokeAllUserRefreshTokens_Call{Call: _e.mock.On("RevokeAllUserRefreshTokens", ctx, userID)}
}

func (_c *MockTokenRepo_RevokeAllUserRefreshTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenRepo_RevokeAllUserRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenRepo_RevokeAllUserRefreshTokens_Call) Return(_a0 error) *MockTokenRepo_RevokeAllUserRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepo_RevokeAllUserRefreshTokens_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTokenRepo_RevokeAllUserRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepo) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepo_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockTokenRepo_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepo_Expecter) RevokeRefreshToken(ctx interface{}, tokenHash interface{}) *MockTokenRepo_RevokeRefreshToken_Call {
	return &MockTokenRepo_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepo_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepo_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepo_RevokeRefreshToken_Call) Return(_a0 error) *MockTokenRepo_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepo_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenRepo_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepo creates a new instance of MockTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepo {
	mock := &MockTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
