// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQuotaRepo is an autogenerated mock type for the QuotaRepo type
type MockQuotaRepo struct {
	mock.Mock
}

type MockQuotaRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaRepo) EXPECT() *MockQuotaRepo_Expecter {
	return &MockQuotaRepo_Expecter{mock: &_m.Mock}
}

// DecrementFreeAnalysesUsed provides a mock function with given fields: ctx, userID
func (_m *MockQuotaRepo) DecrementFreeAnalysesUsed(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementFreeAnalysesUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuotaRepo_DecrementFreeAnalysesUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementFreeAnalysesUsed'
type MockQuotaRepo_DecrementFreeAnalysesUsed_Call struct {
	*mock.Call
}

// DecrementFreeAnalysesUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockQuotaRepo_Expecter) DecrementFreeAnalysesUsed(ctx interface{}, userID interface{}) *MockQuotaRepo_DecrementFreeAnalysesUsed_Call {
	return &MockQuotaRepo_DecrementFreeAnalysesUsed_Call{Call: _e.mock.On("DecrementFreeAnalysesUsed", ctx, userID)}
}

func (_c *MockQuotaRepo_DecrementFreeAnalysesUsed_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockQuotaRepo_DecrementFreeAnalysesUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuotaRepo_DecrementFreeAnalysesUsed_Call) Return(_a0 error) *MockQuotaRepo_DecrementFreeAnalysesUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuotaRepo_DecrementFreeAnalysesUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuotaRepo_DecrementFreeAnalysesUsed_Call {
	_c.Call.Return(run)
	return _c
}

// GetFreeAnalysesUsed provides a mock function with given fields: ctx, userID
func (_m *MockQuotaRepo) GetFreeAnalysesUsed(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFreeAnalysesUsed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaRepo_GetFreeAnalysesUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFreeAnalysesUsed'
type MockQuotaRepo_GetFreeAnalysesUsed_Call struct {
	*mock.Call
}

// GetFreeAnalysesUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockQuotaRepo_Expecter) GetFreeAnalysesUsed(ctx interface{}, userID interface{}) *MockQuotaRepo_GetFreeAnalysesUsed_Call {
	return &MockQuotaRepo_GetFreeAnalysesUsed_Call{Call: _e.mock.On("GetFreeAnalysesUsed", ctx, userID)}
}

func (_c *MockQuotaRepo_GetFreeAnalysesUsed_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockQuotaRepo_GetFreeAnalysesUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuotaRepo_GetFreeAnalysesUsed_Call) Return(_a0 int, _a1 error) *MockQuotaRepo_GetFreeAnalysesUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaRepo_GetFreeAnalysesUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockQuotaRepo_GetFreeAnalysesUsed_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementFreeAnalysesUsed provides a mock function with given fields: ctx, userID
func (_m *MockQuotaRepo) IncrementFreeAnalysesUsed(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementFreeAnalysesUsed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaRepo_IncrementFreeAnalysesUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementFreeAnalysesUsed'
type MockQuotaRepo_IncrementFreeAnalysesUsed_Call struct {
	*mock.Call
}

// IncrementFreeAnalysesUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockQuotaRepo_Expecter) IncrementFreeAnalysesUsed(ctx interface{}, userID interface{}) *MockQuotaRepo_IncrementFreeAnalysesUsed_Call {
	return &MockQuotaRepo_IncrementFreeAnalysesUsed_Call{Call: _e.mock.On("IncrementFreeAnalysesUsed", ctx, userID)}
}

func (_c *MockQuotaRepo_IncrementFreeAnalysesUsed_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockQuotaRepo_IncrementFreeAnalysesUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuotaRepo_IncrementFreeAnalysesUsed_Call) Return(_a0 int, _a1 error) *MockQuotaRepo_IncrementFreeAnalysesUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaRepo_IncrementFreeAnalysesUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockQuotaRepo_IncrementFreeAnalysesUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaRepo creates a new instance of MockQuotaRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaRepo {
	mock := &MockQuotaRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
