// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"
)

// MockKBCacheRepo is an autogenerated mock type for the KBCacheRepo type
type MockKBCacheRepo struct {
	mock.Mock
}

type MockKBCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKBCacheRepo) EXPECT() *MockKBCacheRepo_Expecter {
	return &MockKBCacheRepo_Expecter{mock: &_m.Mock}
}

// FindCachedAnswer provides a mock function with given fields: ctx, question, embedding, trigramThreshold, vectorThreshold
func (_m *MockKBCacheRepo) FindCachedAnswer(ctx context.Context, question string, embedding []float64, trigramThreshold float64, vectorThreshold float64) (*models.KBCacheEntry, error) {
	ret := _m.Called(ctx, question, embedding, trigramThreshold, vectorThreshold)

	if len(ret) == 0 {
		panic("no return value specified for FindCachedAnswer")
	}

	var r0 *models.KBCacheEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []float64, float64, float64) (*models.KBCacheEntry, error)); ok {
		return rf(ctx, question, embedding, trigramThreshold, vectorThreshold)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []float64, float64, float64) *models.KBCacheEntry); ok {
		r0 = rf(ctx, question, embedding, trigramThreshold, vectorThreshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.KBCacheEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []float64, float64, float64) error); ok {
		r1 = rf(ctx, question, embedding, trigramThreshold, vectorThreshold)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKBCacheRepo_FindCachedAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCachedAnswer'
type MockKBCacheRepo_FindCachedAnswer_Call struct {
	*mock.Call
}

// FindCachedAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
//   - embedding []float64
//   - trigramThreshold float64
//   - vectorThreshold float64
func (_e *MockKBCacheRepo_Expecter) FindCachedAnswer(ctx interface{}, question interface{}, embedding interface{}, trigramThreshold interface{}, vectorThreshold interface{}) *MockKBCacheRepo_FindCachedAnswer_Call {
	return &MockKBCacheRepo_FindCachedAnswer_Call{Call: _e.mock.On("FindCachedAnswer", ctx, question, embedding, trigramThreshold, vectorThreshold)}
}

func (_c *MockKBCacheRepo_FindCachedAnswer_Call) Run(run func(ctx context.Context, question string, embedding []float64, trigramThreshold float64, vectorThreshold float64)) *MockKBCacheRepo_FindCachedAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]float64), args[3].(float64), args[4].(float64))
	})
	return _c
}

func (_c *MockKBCacheRepo_FindCachedAnswer_Call) Return(_a0 *models.KBCacheEntry, _a1 error) *MockKBCacheRepo_FindCachedAnswer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKBCacheRepo_FindCachedAnswer_Call) RunAndReturn(run func(context.Context, string, []float64, float64, float64) (*models.KBCacheEntry, error)) *MockKBCacheRepo_FindCachedAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCacheEntry provides a mock function with given fields: ctx, question, embedding, answer, sourceMeta
func (_m *MockKBCacheRepo) SaveCacheEntry(ctx context.Context, question string, embedding []float64, answer string, sourceMeta string) error {
	ret := _m.Called(ctx, question, embedding, answer, sourceMeta)

	if len(ret) == 0 {
		panic("no return value specified for SaveCacheEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []float64, string, string) error); ok {
		r0 = rf(ctx, question, embedding, answer, sourceMeta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKBCacheRepo_SaveCacheEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCacheEntry'
type MockKBCacheRepo_SaveCacheEntry_Call struct {
	*mock.Call
}

// SaveCacheEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
//   - embedding []float64
//   - answer string
//   - sourceMeta string
func (_e *MockKBCacheRepo_Expecter) SaveCacheEntry(ctx interface{}, question interface{}, embedding interface{}, answer interface{}, sourceMeta interface{}) *MockKBCacheRepo_SaveCacheEntry_Call {
	return &MockKBCacheRepo_SaveCacheEntry_Call{Call: _e.mock.On("SaveCacheEntry", ctx, question, embedding, answer, sourceMeta)}
}

func (_c *MockKBCacheRepo_SaveCacheEntry_Call) Run(run func(ctx context.Context, question string, embedding []float64, answer string, sourceMeta string)) *MockKBCacheRepo_SaveCacheEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]float64), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockKBCacheRepo_SaveCacheEntry_Call) Return(_a0 error) *MockKBCacheRepo_SaveCacheEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKBCacheRepo_SaveCacheEntry_Call) RunAndReturn(run func(context.Context, string, []float64, string, string) error) *MockKBCacheRepo_SaveCacheEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKBCacheRepo creates a new instance of MockKBCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKBCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKBCacheRepo {
	mock := &MockKBCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
