// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPromoCodeRepo is an autogenerated mock type for the PromoCodeRepo type
type MockPromoCodeRepo struct {
	mock.Mock
}

type MockPromoCodeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromoCodeRepo) EXPECT() *MockPromoCodeRepo_Expecter {
	return &MockPromoCodeRepo_Expecter{mock: &_m.Mock}
}

// CreatePromoCode provides a mock function with given fields: ctx, promo
func (_m *MockPromoCodeRepo) CreatePromoCode(ctx context.Context, promo *models.PromoCode) error {
	ret := _m.Called(ctx, promo)

	if len(ret) == 0 {
		panic("no return value specified for CreatePromoCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PromoCode) error); ok {
		r0 = rf(ctx, promo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPromoCodeRepo_CreatePromoCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePromoCode'
type MockPromoCodeRepo_CreatePromoCode_Call struct {
	*mock.Call
}

// CreatePromoCode is a helper method to define mock.On call
//   - ctx context.Context
//   - promo *models.PromoCode
func (_e *MockPromoCodeRepo_Expecter) CreatePromoCode(ctx interface{}, promo interface{}) *MockPromoCodeRepo_CreatePromoCode_Call {
	return &MockPromoCodeRepo_CreatePromoCode_Call{Call: _e.mock.On("CreatePromoCode", ctx, promo)}
}

func (_c *MockPromoCodeRepo_CreatePromoCode_Call) Run(run func(ctx context.Context, promo *models.PromoCode)) *MockPromoCodeRepo_CreatePromoCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PromoCode))
	})
	return _c
}

func (_c *MockPromoCodeRepo_CreatePromoCode_Call) Return(_a0 error) *MockPromoCodeRepo_CreatePromoCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromoCodeRepo_CreatePromoCode_Call) RunAndReturn(run func(context.Context, *models.PromoCode) error) *MockPromoCodeRepo_CreatePromoCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetPromoCodeByCode provides a mock function with given fields: ctx, code
func (_m *MockPromoCodeRepo) GetPromoCodeByCode(ctx context.Context, code string) (*models.PromoCode, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetPromoCodeByCode")
	}

	var r0 *models.PromoCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PromoCode, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PromoCode); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PromoCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPromoCodeRepo_GetPromoCodeByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPromoCodeByCode'
type MockPromoCodeRepo_GetPromoCodeByCode_Call struct {
	*mock.Call
}

// GetPromoCodeByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockPromoCodeRepo_Expecter) GetPromoCodeByCode(ctx interface{}, code interface{}) *MockPromoCodeRepo_GetPromoCodeByCode_Call {
	return &MockPromoCodeRepo_GetPromoCodeByCode_Call{Call: _e.mock.On("GetPromoCodeByCode", ctx, code)}
}

func (_c *MockPromoCodeRepo_GetPromoCodeByCode_Call) Run(run func(ctx context.Context, code string)) *MockPromoCodeRepo_GetPromoCodeByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPromoCodeRepo_GetPromoCodeByCode_Call) Return(_a0 *models.PromoCode, _a1 error) *MockPromoCodeRepo_GetPromoCodeByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPromoCodeRepo_GetPromoCodeByCode_Call) RunAndReturn(run func(context.Context, string) (*models.PromoCode, error)) *MockPromoCodeRepo_GetPromoCodeByCode_Call {
	_c.Call.Return(run)
	return _c
}

// RecordPromoCodeUsage provides a mock function with given fields: ctx, usage
func (_m *MockPromoCodeRepo) RecordPromoCodeUsage(ctx context.Context, usage *models.PromoCodeUsage) error {
	ret := _m.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for RecordPromoCodeUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PromoCodeUsage) error); ok {
		r0 = rf(ctx, usage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPromoCodeRepo_RecordPromoCodeUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPromoCodeUsage'
type MockPromoCodeRepo_RecordPromoCodeUsage_Call struct {
	*mock.Call
}

// RecordPromoCodeUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - usage *models.PromoCodeUsage
func (_e *MockPromoCodeRepo_Expecter) RecordPromoCodeUsage(ctx interface{}, usage interface{}) *MockPromoCodeRepo_RecordPromoCodeUsage_Call {
	return &MockPromoCodeRepo_RecordPromoCodeUsage_Call{Call: _e.mock.On("RecordPromoCodeUsage", ctx, usage)}
}

func (_c *MockPromoCodeRepo_RecordPromoCodeUsage_Call) Run(run func(ctx context.Context, usage *models.PromoCodeUsage)) *MockPromoCodeRepo_RecordPromoCodeUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PromoCodeUsage))
	})
	return _c
}

func (_c *MockPromoCodeRepo_RecordPromoCodeUsage_Call) Return(_a0 error) *MockPromoCodeRepo_RecordPromoCodeUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromoCodeRepo_RecordPromoCodeUsage_Call) RunAndReturn(run func(context.Context, *models.PromoCodeUsage) error) *MockPromoCodeRepo_RecordPromoCodeUsage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePromoCodeUsedCount provides a mock function with given fields: ctx, promoCodeID
func (_m *MockPromoCodeRepo) UpdatePromoCodeUsedCount(ctx context.Context, promoCodeID uuid.UUID) error {
	ret := _m.Called(ctx, promoCodeID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePromoCodeUsedCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, promoCodeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePromoCodeUsedCount'
type MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call struct {
	*mock.Call
}

// UpdatePromoCodeUsedCount is a helper method to define mock.On call
//   - ctx context.Context
//   - promoCodeID uuid.UUID
func (_e *MockPromoCodeRepo_Expecter) UpdatePromoCodeUsedCount(ctx interface{}, promoCodeID interface{}) *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call {
	return &MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call{Call: _e.mock.On("UpdatePromoCodeUsedCount", ctx, promoCodeID)}
}

func (_c *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call) Run(run func(ctx context.Context, promoCodeID uuid.UUID)) *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call) Return(_a0 error) *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockPromoCodeRepo_UpdatePromoCodeUsedCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPromoCodeRepo creates a new instance of MockPromoCodeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromoCodeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromoCodeRepo {
	mock := &MockPromoCodeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
