// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	repository "github.com/fedutinova/smartheart/back-api/repository"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AssignRoleToUser provides a mock function with given fields: ctx, userID, roleName
func (_m *MockStore) AssignRoleToUser(ctx context.Context, userID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, userID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_AssignRoleToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoleToUser'
type MockStore_AssignRoleToUser_Call struct {
	*mock.Call
}

// AssignRoleToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roleName string
func (_e *MockStore_Expecter) AssignRoleToUser(ctx interface{}, userID interface{}, roleName interface{}) *MockStore_AssignRoleToUser_Call {
	return &MockStore_AssignRoleToUser_Call{Call: _e.mock.On("AssignRoleToUser", ctx, userID, roleName)}
}

func (_c *MockStore_AssignRoleToUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, roleName string)) *MockStore_AssignRoleToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockStore_AssignRoleToUser_Call) Return(_a0 error) *MockStore_AssignRoleToUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_AssignRoleToUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockStore_AssignRoleToUser_Call {
	_c.Call.Return(run)
	return _c
}

// CountRequestsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockStore) CountRequestsByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountRequestsByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CountRequestsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRequestsByUserID'
type MockStore_CountRequestsByUserID_Call struct {
	*mock.Call
}

// CountRequestsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) CountRequestsByUserID(ctx interface{}, userID interface{}) *MockStore_CountRequestsByUserID_Call {
	return &MockStore_CountRequestsByUserID_Call{Call: _e.mock.On("CountRequestsByUserID", ctx, userID)}
}

func (_c *MockStore_CountRequestsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_CountRequestsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_CountRequestsByUserID_Call) Return(_a0 int, _a1 error) *MockStore_CountRequestsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CountRequestsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockStore_CountRequestsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function with given fields: ctx, file
func (_m *MockStore) CreateFile(ctx context.Context, file *models.File) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.File) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockStore_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.File
func (_e *MockStore_Expecter) CreateFile(ctx interface{}, file interface{}) *MockStore_CreateFile_Call {
	return &MockStore_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, file)}
}

func (_c *MockStore_CreateFile_Call) Run(run func(ctx context.Context, file *models.File)) *MockStore_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.File))
	})
	return _c
}

func (_c *MockStore_CreateFile_Call) Return(_a0 error) *MockStore_CreateFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateFile_Call) RunAndReturn(run func(context.Context, *models.File) error) *MockStore_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRAGFeedback provides a mock function with given fields: ctx, feedback
func (_m *MockStore) CreateRAGFeedback(ctx context.Context, feedback *models.RAGFeedback) error {
	ret := _m.Called(ctx, feedback)

	if len(ret) == 0 {
		panic("no return value specified for CreateRAGFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RAGFeedback) error); ok {
		r0 = rf(ctx, feedback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateRAGFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRAGFeedback'
type MockStore_CreateRAGFeedback_Call struct {
	*mock.Call
}

// CreateRAGFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - feedback *models.RAGFeedback
func (_e *MockStore_Expecter) CreateRAGFeedback(ctx interface{}, feedback interface{}) *MockStore_CreateRAGFeedback_Call {
	return &MockStore_CreateRAGFeedback_Call{Call: _e.mock.On("CreateRAGFeedback", ctx, feedback)}
}

func (_c *MockStore_CreateRAGFeedback_Call) Run(run func(ctx context.Context, feedback *models.RAGFeedback)) *MockStore_CreateRAGFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RAGFeedback))
	})
	return _c
}

func (_c *MockStore_CreateRAGFeedback_Call) Return(_a0 error) *MockStore_CreateRAGFeedback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateRAGFeedback_Call) RunAndReturn(run func(context.Context, *models.RAGFeedback) error) *MockStore_CreateRAGFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockStore) CreateRefreshToken(ctx context.Context, token *models.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockStore_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.RefreshToken
func (_e *MockStore_Expecter) CreateRefreshToken(ctx interface{}, token interface{}) *MockStore_CreateRefreshToken_Call {
	return &MockStore_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, token)}
}

func (_c *MockStore_CreateRefreshToken_Call) Run(run func(ctx context.Context, token *models.RefreshToken)) *MockStore_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RefreshToken))
	})
	return _c
}

func (_c *MockStore_CreateRefreshToken_Call) Return(_a0 error) *MockStore_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateRefreshToken_Call) RunAndReturn(run func(context.Context, *models.RefreshToken) error) *MockStore_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequest provides a mock function with given fields: ctx, req
func (_m *MockStore) CreateRequest(ctx context.Context, req *models.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockStore_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
func (_e *MockStore_Expecter) CreateRequest(ctx interface{}, req interface{}) *MockStore_CreateRequest_Call {
	return &MockStore_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, req)}
}

func (_c *MockStore_CreateRequest_Call) Run(run func(ctx context.Context, req *models.Request)) *MockStore_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request))
	})
	return _c
}

func (_c *MockStore_CreateRequest_Call) Return(_a0 error) *MockStore_CreateRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateRequest_Call) RunAndReturn(run func(context.Context, *models.Request) error) *MockStore_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResponse provides a mock function with given fields: ctx, resp
func (_m *MockStore) CreateResponse(ctx context.Context, resp *models.Response) error {
	ret := _m.Called(ctx, resp)

	if len(ret) == 0 {
		panic("no return value specified for CreateResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Response) error); ok {
		r0 = rf(ctx, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResponse'
type MockStore_CreateResponse_Call struct {
	*mock.Call
}

// CreateResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - resp *models.Response
func (_e *MockStore_Expecter) CreateResponse(ctx interface{}, resp interface{}) *MockStore_CreateResponse_Call {
	return &MockStore_CreateResponse_Call{Call: _e.mock.On("CreateResponse", ctx, resp)}
}

func (_c *MockStore_CreateResponse_Call) Run(run func(ctx context.Context, resp *models.Response)) *MockStore_CreateResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Response))
	})
	return _c
}

func (_c *MockStore_CreateResponse_Call) Return(_a0 error) *MockStore_CreateResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateResponse_Call) RunAndReturn(run func(context.Context, *models.Response) error) *MockStore_CreateResponse_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockStore) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockStore_Expecter) CreateUser(ctx interface{}, user interface{}) *MockStore_CreateUser_Call {
	return &MockStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockStore_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockStore_CreateUser_Call) Return(_a0 error) *MockStore_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyUsage provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetDailyUsage(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyUsage")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyUsage'
type MockStore_GetDailyUsage_Call struct {
	*mock.Call
}

// GetDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) GetDailyUsage(ctx interface{}, userID interface{}) *MockStore_GetDailyUsage_Call {
	return &MockStore_GetDailyUsage_Call{Call: _e.mock.On("GetDailyUsage", ctx, userID)}
}

func (_c *MockStore_GetDailyUsage_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_GetDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetDailyUsage_Call) Return(_a0 int, _a1 error) *MockStore_GetDailyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetDailyUsage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockStore_GetDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByRequestID provides a mock function with given fields: ctx, requestID
func (_m *MockStore) GetFilesByRequestID(ctx context.Context, requestID uuid.UUID) ([]models.File, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByRequestID")
	}

	var r0 []models.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.File, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.File); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetFilesByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByRequestID'
type MockStore_GetFilesByRequestID_Call struct {
	*mock.Call
}

// GetFilesByRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockStore_Expecter) GetFilesByRequestID(ctx interface{}, requestID interface{}) *MockStore_GetFilesByRequestID_Call {
	return &MockStore_GetFilesByRequestID_Call{Call: _e.mock.On("GetFilesByRequestID", ctx, requestID)}
}

func (_c *MockStore_GetFilesByRequestID_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockStore_GetFilesByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetFilesByRequestID_Call) Return(_a0 []models.File, _a1 error) *MockStore_GetFilesByRequestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetFilesByRequestID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.File, error)) *MockStore_GetFilesByRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentRequestsWithResponses provides a mock function with given fields: ctx, userID, limit
func (_m *MockStore) GetRecentRequestsWithResponses(ctx context.Context, userID uuid.UUID, limit int) ([]models.Request, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentRequestsWithResponses")
	}

	var r0 []models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]models.Request, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []models.Request); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetRecentRequestsWithResponses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentRequestsWithResponses'
type MockStore_GetRecentRequestsWithResponses_Call struct {
	*mock.Call
}

// GetRecentRequestsWithResponses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
func (_e *MockStore_Expecter) GetRecentRequestsWithResponses(ctx interface{}, userID interface{}, limit interface{}) *MockStore_GetRecentRequestsWithResponses_Call {
	return &MockStore_GetRecentRequestsWithResponses_Call{Call: _e.mock.On("GetRecentRequestsWithResponses", ctx, userID, limit)}
}

func (_c *MockStore_GetRecentRequestsWithResponses_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int)) *MockStore_GetRecentRequestsWithResponses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockStore_GetRecentRequestsWithResponses_Call) Return(_a0 []models.Request, _a1 error) *MockStore_GetRecentRequestsWithResponses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetRecentRequestsWithResponses_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]models.Request, error)) *MockStore_GetRecentRequestsWithResponses_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockStore) GetRefreshToken(ctx context.Context, tokenHash string) (*models.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockStore_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockStore_Expecter) GetRefreshToken(ctx interface{}, tokenHash interface{}) *MockStore_GetRefreshToken_Call {
	return &MockStore_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenHash)}
}

func (_c *MockStore_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockStore_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetRefreshToken_Call) Return(_a0 *models.RefreshToken, _a1 error) *MockStore_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*models.RefreshToken, error)) *MockStore_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestByID provides a mock function with given fields: ctx, id
func (_m *MockStore) GetRequestByID(ctx context.Context, id uuid.UUID) (*models.Request, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestByID")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Request, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestByID'
type MockStore_GetRequestByID_Call struct {
	*mock.Call
}

// GetRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) GetRequestByID(ctx interface{}, id interface{}) *MockStore_GetRequestByID_Call {
	return &MockStore_GetRequestByID_Call{Call: _e.mock.On("GetRequestByID", ctx, id)}
}

func (_c *MockStore_GetRequestByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_GetRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetRequestByID_Call) Return(_a0 *models.Request, _a1 error) *MockStore_GetRequestByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetRequestByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Request, error)) *MockStore_GetRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestsByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockStore) GetRequestsByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]models.Request, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestsByUserID")
	}

	var r0 []models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]models.Request, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []models.Request); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetRequestsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestsByUserID'
type MockStore_GetRequestsByUserID_Call struct {
	*mock.Call
}

// GetRequestsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockStore_Expecter) GetRequestsByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockStore_GetRequestsByUserID_Call {
	return &MockStore_GetRequestsByUserID_Call{Call: _e.mock.On("GetRequestsByUserID", ctx, userID, limit, offset)}
}

func (_c *MockStore_GetRequestsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockStore_GetRequestsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockStore_GetRequestsByUserID_Call) Return(_a0 []models.Request, _a1 error) *MockStore_GetRequestsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetRequestsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]models.Request, error)) *MockStore_GetRequestsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetResponseByRequestID provides a mock function with given fields: ctx, requestID
func (_m *MockStore) GetResponseByRequestID(ctx context.Context, requestID uuid.UUID) (*models.Response, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetResponseByRequestID")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Response, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Response); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetResponseByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResponseByRequestID'
type MockStore_GetResponseByRequestID_Call struct {
	*mock.Call
}

// GetResponseByRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockStore_Expecter) GetResponseByRequestID(ctx interface{}, requestID interface{}) *MockStore_GetResponseByRequestID_Call {
	return &MockStore_GetResponseByRequestID_Call{Call: _e.mock.On("GetResponseByRequestID", ctx, requestID)}
}

func (_c *MockStore_GetResponseByRequestID_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockStore_GetResponseByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetResponseByRequestID_Call) Return(_a0 *models.Response, _a1 error) *MockStore_GetResponseByRequestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetResponseByRequestID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Response, error)) *MockStore_GetResponseByRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockStore) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStore_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockStore_GetUserByEmail_Call {
	return &MockStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) Return(_a0 *models.User, _a1 error) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetUserByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockStore_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockStore_GetUserByID_Call {
	return &MockStore_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockStore_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockStore_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.User, error)) *MockStore_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementDailyUsage provides a mock function with given fields: ctx, userID
func (_m *MockStore) IncrementDailyUsage(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementDailyUsage")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_IncrementDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementDailyUsage'
type MockStore_IncrementDailyUsage_Call struct {
	*mock.Call
}

// IncrementDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) IncrementDailyUsage(ctx interface{}, userID interface{}) *MockStore_IncrementDailyUsage_Call {
	return &MockStore_IncrementDailyUsage_Call{Call: _e.mock.On("IncrementDailyUsage", ctx, userID)}
}

func (_c *MockStore_IncrementDailyUsage_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_IncrementDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_IncrementDailyUsage_Call) Return(_a0 int, _a1 error) *MockStore_IncrementDailyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_IncrementDailyUsage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockStore_IncrementDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// LoadRolePermissions provides a mock function with given fields: ctx
func (_m *MockStore) LoadRolePermissions(ctx context.Context) (map[string][]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadRolePermissions")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string][]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string][]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRolePermissions'
type MockStore_LoadRolePermissions_Call struct {
	*mock.Call
}

// LoadRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) LoadRolePermissions(ctx interface{}) *MockStore_LoadRolePermissions_Call {
	return &MockStore_LoadRolePermissions_Call{Call: _e.mock.On("LoadRolePermissions", ctx)}
}

func (_c *MockStore_LoadRolePermissions_Call) Run(run func(ctx context.Context)) *MockStore_LoadRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_LoadRolePermissions_Call) Return(_a0 map[string][]string, _a1 error) *MockStore_LoadRolePermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadRolePermissions_Call) RunAndReturn(run func(context.Context) (map[string][]string, error)) *MockStore_LoadRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockStore) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Ping(ctx interface{}) *MockStore_Ping_Call {
	return &MockStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStore_Ping_Call) Run(run func(ctx context.Context)) *MockStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_Ping_Call) Return(_a0 error) *MockStore_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Ping_Call) RunAndReturn(run func(context.Context) error) *MockStore_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockStore) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockStore_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockStore_Expecter) RevokeRefreshToken(ctx interface{}, tokenHash interface{}) *MockStore_RevokeRefreshToken_Call {
	return &MockStore_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenHash)}
}

func (_c *MockStore_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockStore_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_RevokeRefreshToken_Call) Return(_a0 error) *MockStore_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockStore_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RunTx provides a mock function with given fields: ctx, fn
func (_m *MockStore) RunTx(ctx context.Context, fn func(pgx.Tx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(pgx.Tx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_RunTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTx'
type MockStore_RunTx_Call struct {
	*mock.Call
}

// RunTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(pgx.Tx) error
func (_e *MockStore_Expecter) RunTx(ctx interface{}, fn interface{}) *MockStore_RunTx_Call {
	return &MockStore_RunTx_Call{Call: _e.mock.On("RunTx", ctx, fn)}
}

func (_c *MockStore_RunTx_Call) Run(run func(ctx context.Context, fn func(pgx.Tx) error)) *MockStore_RunTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(pgx.Tx) error))
	})
	return _c
}

func (_c *MockStore_RunTx_Call) Return(_a0 error) *MockStore_RunTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_RunTx_Call) RunAndReturn(run func(context.Context, func(pgx.Tx) error) error) *MockStore_RunTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequestStatus provides a mock function with given fields: ctx, requestID, status
func (_m *MockStore) UpdateRequestStatus(ctx context.Context, requestID uuid.UUID, status string) error {
	ret := _m.Called(ctx, requestID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, requestID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdateRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequestStatus'
type MockStore_UpdateRequestStatus_Call struct {
	*mock.Call
}

// UpdateRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - status string
func (_e *MockStore_Expecter) UpdateRequestStatus(ctx interface{}, requestID interface{}, status interface{}) *MockStore_UpdateRequestStatus_Call {
	return &MockStore_UpdateRequestStatus_Call{Call: _e.mock.On("UpdateRequestStatus", ctx, requestID, status)}
}

func (_c *MockStore_UpdateRequestStatus_Call) Run(run func(ctx context.Context, requestID uuid.UUID, status string)) *MockStore_UpdateRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockStore_UpdateRequestStatus_Call) Return(_a0 error) *MockStore_UpdateRequestStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdateRequestStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockStore_UpdateRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *MockStore) WithTx(tx pgx.Tx) repository.Store {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.Store
	if rf, ok := ret.Get(0).(func(pgx.Tx) repository.Store); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Store)
		}
	}

	return r0
}

// MockStore_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockStore_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *MockStore_Expecter) WithTx(tx interface{}) *MockStore_WithTx_Call {
	return &MockStore_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockStore_WithTx_Call) Run(run func(tx pgx.Tx)) *MockStore_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.Tx))
	})
	return _c
}

func (_c *MockStore_WithTx_Call) Return(_a0 repository.Store) *MockStore_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_WithTx_Call) RunAndReturn(run func(pgx.Tx) repository.Store) *MockStore_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CancelPayment provides a mock function with given fields: ctx, yookassaID
func (_m *MockStore) CancelPayment(ctx context.Context, yookassaID string) error {
	ret := _m.Called(ctx, yookassaID)
	if len(ret) == 0 {
		panic("no return value specified for CancelPayment")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, yookassaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConfirmPayment provides a mock function with given fields: ctx, yookassaID
func (_m *MockStore) ConfirmPayment(ctx context.Context, yookassaID string) error {
	ret := _m.Called(ctx, yookassaID)
	if len(ret) == 0 {
		panic("no return value specified for ConfirmPayment")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, yookassaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CreatePayment provides a mock function with given fields: ctx, p
func (_m *MockStore) CreatePayment(ctx context.Context, p *models.Payment) error {
	ret := _m.Called(ctx, p)
	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DecrementPaidAnalyses provides a mock function with given fields: ctx, userID
func (_m *MockStore) DecrementPaidAnalyses(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)
	if len(ret) == 0 {
		panic("no return value specified for DecrementPaidAnalyses")
	}
	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetPaidAnalysesRemaining provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetPaidAnalysesRemaining(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)
	if len(ret) == 0 {
		panic("no return value specified for GetPaidAnalysesRemaining")
	}
	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetPaymentsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetPaymentsByUserID(ctx context.Context, userID uuid.UUID) ([]models.Payment, error) {
	ret := _m.Called(ctx, userID)
	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsByUserID")
	}
	var r0 []models.Payment
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Payment); ok {
		r0 = rf(ctx, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.Payment)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
