// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockPaymentRepo is an autogenerated mock type for the PaymentRepo type
type MockPaymentRepo struct {
	mock.Mock
}

type MockPaymentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepo) EXPECT() *MockPaymentRepo_Expecter {
	return &MockPaymentRepo_Expecter{mock: &_m.Mock}
}

// CancelPayment provides a mock function with given fields: ctx, yookassaID
func (_m *MockPaymentRepo) CancelPayment(ctx context.Context, yookassaID string) error {
	ret := _m.Called(ctx, yookassaID)

	if len(ret) == 0 {
		panic("no return value specified for CancelPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, yookassaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_CancelPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPayment'
type MockPaymentRepo_CancelPayment_Call struct {
	*mock.Call
}

// CancelPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - yookassaID string
func (_e *MockPaymentRepo_Expecter) CancelPayment(ctx interface{}, yookassaID interface{}) *MockPaymentRepo_CancelPayment_Call {
	return &MockPaymentRepo_CancelPayment_Call{Call: _e.mock.On("CancelPayment", ctx, yookassaID)}
}

func (_c *MockPaymentRepo_CancelPayment_Call) Run(run func(ctx context.Context, yookassaID string)) *MockPaymentRepo_CancelPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_CancelPayment_Call) Return(_a0 error) *MockPaymentRepo_CancelPayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_CancelPayment_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentRepo_CancelPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CancelStalePayments provides a mock function with given fields: ctx, olderThan
func (_m *MockPaymentRepo) CancelStalePayments(ctx context.Context, olderThan time.Duration) (int, error) {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for CancelStalePayments")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (int, error)); ok {
		return rf(ctx, olderThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) int); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_CancelStalePayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelStalePayments'
type MockPaymentRepo_CancelStalePayments_Call struct {
	*mock.Call
}

// CancelStalePayments is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *MockPaymentRepo_Expecter) CancelStalePayments(ctx interface{}, olderThan interface{}) *MockPaymentRepo_CancelStalePayments_Call {
	return &MockPaymentRepo_CancelStalePayments_Call{Call: _e.mock.On("CancelStalePayments", ctx, olderThan)}
}

func (_c *MockPaymentRepo_CancelStalePayments_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *MockPaymentRepo_CancelStalePayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockPaymentRepo_CancelStalePayments_Call) Return(_a0 int, _a1 error) *MockPaymentRepo_CancelStalePayments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_CancelStalePayments_Call) RunAndReturn(run func(context.Context, time.Duration) (int, error)) *MockPaymentRepo_CancelStalePayments_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmPayment provides a mock function with given fields: ctx, yookassaID
func (_m *MockPaymentRepo) ConfirmPayment(ctx context.Context, yookassaID string) error {
	ret := _m.Called(ctx, yookassaID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, yookassaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_ConfirmPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmPayment'
type MockPaymentRepo_ConfirmPayment_Call struct {
	*mock.Call
}

// ConfirmPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - yookassaID string
func (_e *MockPaymentRepo_Expecter) ConfirmPayment(ctx interface{}, yookassaID interface{}) *MockPaymentRepo_ConfirmPayment_Call {
	return &MockPaymentRepo_ConfirmPayment_Call{Call: _e.mock.On("ConfirmPayment", ctx, yookassaID)}
}

func (_c *MockPaymentRepo_ConfirmPayment_Call) Run(run func(ctx context.Context, yookassaID string)) *MockPaymentRepo_ConfirmPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_ConfirmPayment_Call) Return(_a0 error) *MockPaymentRepo_ConfirmPayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_ConfirmPayment_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentRepo_ConfirmPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayment provides a mock function with given fields: ctx, p
func (_m *MockPaymentRepo) CreatePayment(ctx context.Context, p *models.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockPaymentRepo_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - p *models.Payment
func (_e *MockPaymentRepo_Expecter) CreatePayment(ctx interface{}, p interface{}) *MockPaymentRepo_CreatePayment_Call {
	return &MockPaymentRepo_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, p)}
}

func (_c *MockPaymentRepo_CreatePayment_Call) Run(run func(ctx context.Context, p *models.Payment)) *MockPaymentRepo_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Payment))
	})
	return _c
}

func (_c *MockPaymentRepo_CreatePayment_Call) Return(_a0 error) *MockPaymentRepo_CreatePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_CreatePayment_Call) RunAndReturn(run func(context.Context, *models.Payment) error) *MockPaymentRepo_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementPaidAnalyses provides a mock function with given fields: ctx, userID
func (_m *MockPaymentRepo) DecrementPaidAnalyses(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementPaidAnalyses")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_DecrementPaidAnalyses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementPaidAnalyses'
type MockPaymentRepo_DecrementPaidAnalyses_Call struct {
	*mock.Call
}

// DecrementPaidAnalyses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPaymentRepo_Expecter) DecrementPaidAnalyses(ctx interface{}, userID interface{}) *MockPaymentRepo_DecrementPaidAnalyses_Call {
	return &MockPaymentRepo_DecrementPaidAnalyses_Call{Call: _e.mock.On("DecrementPaidAnalyses", ctx, userID)}
}

func (_c *MockPaymentRepo_DecrementPaidAnalyses_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPaymentRepo_DecrementPaidAnalyses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepo_DecrementPaidAnalyses_Call) Return(_a0 int, _a1 error) *MockPaymentRepo_DecrementPaidAnalyses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_DecrementPaidAnalyses_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockPaymentRepo_DecrementPaidAnalyses_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaidAnalysesRemaining provides a mock function with given fields: ctx, userID
func (_m *MockPaymentRepo) GetPaidAnalysesRemaining(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaidAnalysesRemaining")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_GetPaidAnalysesRemaining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaidAnalysesRemaining'
type MockPaymentRepo_GetPaidAnalysesRemaining_Call struct {
	*mock.Call
}

// GetPaidAnalysesRemaining is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPaymentRepo_Expecter) GetPaidAnalysesRemaining(ctx interface{}, userID interface{}) *MockPaymentRepo_GetPaidAnalysesRemaining_Call {
	return &MockPaymentRepo_GetPaidAnalysesRemaining_Call{Call: _e.mock.On("GetPaidAnalysesRemaining", ctx, userID)}
}

func (_c *MockPaymentRepo_GetPaidAnalysesRemaining_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPaymentRepo_GetPaidAnalysesRemaining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepo_GetPaidAnalysesRemaining_Call) Return(_a0 int, _a1 error) *MockPaymentRepo_GetPaidAnalysesRemaining_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_GetPaidAnalysesRemaining_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockPaymentRepo_GetPaidAnalysesRemaining_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockPaymentRepo) GetPaymentsByUserID(ctx context.Context, userID uuid.UUID) ([]models.Payment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsByUserID")
	}

	var r0 []models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Payment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Payment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_GetPaymentsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentsByUserID'
type MockPaymentRepo_GetPaymentsByUserID_Call struct {
	*mock.Call
}

// GetPaymentsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPaymentRepo_Expecter) GetPaymentsByUserID(ctx interface{}, userID interface{}) *MockPaymentRepo_GetPaymentsByUserID_Call {
	return &MockPaymentRepo_GetPaymentsByUserID_Call{Call: _e.mock.On("GetPaymentsByUserID", ctx, userID)}
}

func (_c *MockPaymentRepo_GetPaymentsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPaymentRepo_GetPaymentsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepo_GetPaymentsByUserID_Call) Return(_a0 []models.Payment, _a1 error) *MockPaymentRepo_GetPaymentsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_GetPaymentsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Payment, error)) *MockPaymentRepo_GetPaymentsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionExpiresAt provides a mock function with given fields: ctx, userID
func (_m *MockPaymentRepo) GetSubscriptionExpiresAt(ctx context.Context, userID uuid.UUID) (*time.Time, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionExpiresAt")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*time.Time, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *time.Time); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_GetSubscriptionExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionExpiresAt'
type MockPaymentRepo_GetSubscriptionExpiresAt_Call struct {
	*mock.Call
}

// GetSubscriptionExpiresAt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPaymentRepo_Expecter) GetSubscriptionExpiresAt(ctx interface{}, userID interface{}) *MockPaymentRepo_GetSubscriptionExpiresAt_Call {
	return &MockPaymentRepo_GetSubscriptionExpiresAt_Call{Call: _e.mock.On("GetSubscriptionExpiresAt", ctx, userID)}
}

func (_c *MockPaymentRepo_GetSubscriptionExpiresAt_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPaymentRepo_GetSubscriptionExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepo_GetSubscriptionExpiresAt_Call) Return(_a0 *time.Time, _a1 error) *MockPaymentRepo_GetSubscriptionExpiresAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_GetSubscriptionExpiresAt_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*time.Time, error)) *MockPaymentRepo_GetSubscriptionExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// HasPendingPayment provides a mock function with given fields: ctx, userID, paymentType
func (_m *MockPaymentRepo) HasPendingPayment(ctx context.Context, userID uuid.UUID, paymentType string) (bool, error) {
	ret := _m.Called(ctx, userID, paymentType)

	if len(ret) == 0 {
		panic("no return value specified for HasPendingPayment")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, userID, paymentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, userID, paymentType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, paymentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_HasPendingPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPendingPayment'
type MockPaymentRepo_HasPendingPayment_Call struct {
	*mock.Call
}

// HasPendingPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - paymentType string
func (_e *MockPaymentRepo_Expecter) HasPendingPayment(ctx interface{}, userID interface{}, paymentType interface{}) *MockPaymentRepo_HasPendingPayment_Call {
	return &MockPaymentRepo_HasPendingPayment_Call{Call: _e.mock.On("HasPendingPayment", ctx, userID, paymentType)}
}

func (_c *MockPaymentRepo_HasPendingPayment_Call) Run(run func(ctx context.Context, userID uuid.UUID, paymentType string)) *MockPaymentRepo_HasPendingPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_HasPendingPayment_Call) Return(_a0 bool, _a1 error) *MockPaymentRepo_HasPendingPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_HasPendingPayment_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (bool, error)) *MockPaymentRepo_HasPendingPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepo creates a new instance of MockPaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepo {
	mock := &MockPaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
