// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/fedutinova/smartheart/back-api/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockAdminRepo is an autogenerated mock type for the AdminRepo type
type MockAdminRepo struct {
	mock.Mock
}

type MockAdminRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepo) EXPECT() *MockAdminRepo_Expecter {
	return &MockAdminRepo_Expecter{mock: &_m.Mock}
}

// GetAdminStats provides a mock function with given fields: ctx
func (_m *MockAdminRepo) GetAdminStats(ctx context.Context) (*repository.AdminStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminStats")
	}

	var r0 *repository.AdminStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*repository.AdminStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *repository.AdminStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.AdminStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepo_GetAdminStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminStats'
type MockAdminRepo_GetAdminStats_Call struct {
	*mock.Call
}

// GetAdminStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminRepo_Expecter) GetAdminStats(ctx interface{}) *MockAdminRepo_GetAdminStats_Call {
	return &MockAdminRepo_GetAdminStats_Call{Call: _e.mock.On("GetAdminStats", ctx)}
}

func (_c *MockAdminRepo_GetAdminStats_Call) Run(run func(ctx context.Context)) *MockAdminRepo_GetAdminStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminRepo_GetAdminStats_Call) Return(_a0 *repository.AdminStats, _a1 error) *MockAdminRepo_GetAdminStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepo_GetAdminStats_Call) RunAndReturn(run func(context.Context) (*repository.AdminStats, error)) *MockAdminRepo_GetAdminStats_Call {
	_c.Call.Return(run)
	return _c
}

// ListPayments provides a mock function with given fields: ctx, limit, offset
func (_m *MockAdminRepo) ListPayments(ctx context.Context, limit int, offset int) ([]repository.AdminPaymentRow, int, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 []repository.AdminPaymentRow
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repository.AdminPaymentRow, int, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repository.AdminPaymentRow); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.AdminPaymentRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdminRepo_ListPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPayments'
type MockAdminRepo_ListPayments_Call struct {
	*mock.Call
}

// ListPayments is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAdminRepo_Expecter) ListPayments(ctx interface{}, limit interface{}, offset interface{}) *MockAdminRepo_ListPayments_Call {
	return &MockAdminRepo_ListPayments_Call{Call: _e.mock.On("ListPayments", ctx, limit, offset)}
}

func (_c *MockAdminRepo_ListPayments_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAdminRepo_ListPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAdminRepo_ListPayments_Call) Return(_a0 []repository.AdminPaymentRow, _a1 int, _a2 error) *MockAdminRepo_ListPayments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdminRepo_ListPayments_Call) RunAndReturn(run func(context.Context, int, int) ([]repository.AdminPaymentRow, int, error)) *MockAdminRepo_ListPayments_Call {
	_c.Call.Return(run)
	return _c
}

// ListRAGFeedback provides a mock function with given fields: ctx, limit, offset
func (_m *MockAdminRepo) ListRAGFeedback(ctx context.Context, limit int, offset int) ([]repository.AdminFeedbackRow, int, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListRAGFeedback")
	}

	var r0 []repository.AdminFeedbackRow
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repository.AdminFeedbackRow, int, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repository.AdminFeedbackRow); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.AdminFeedbackRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdminRepo_ListRAGFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRAGFeedback'
type MockAdminRepo_ListRAGFeedback_Call struct {
	*mock.Call
}

// ListRAGFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAdminRepo_Expecter) ListRAGFeedback(ctx interface{}, limit interface{}, offset interface{}) *MockAdminRepo_ListRAGFeedback_Call {
	return &MockAdminRepo_ListRAGFeedback_Call{Call: _e.mock.On("ListRAGFeedback", ctx, limit, offset)}
}

func (_c *MockAdminRepo_ListRAGFeedback_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAdminRepo_ListRAGFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAdminRepo_ListRAGFeedback_Call) Return(_a0 []repository.AdminFeedbackRow, _a1 int, _a2 error) *MockAdminRepo_ListRAGFeedback_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdminRepo_ListRAGFeedback_Call) RunAndReturn(run func(context.Context, int, int) ([]repository.AdminFeedbackRow, int, error)) *MockAdminRepo_ListRAGFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, limit, offset, search
func (_m *MockAdminRepo) ListUsers(ctx context.Context, limit int, offset int, search string) ([]repository.AdminUserRow, int, error) {
	ret := _m.Called(ctx, limit, offset, search)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []repository.AdminUserRow
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) ([]repository.AdminUserRow, int, error)); ok {
		return rf(ctx, limit, offset, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []repository.AdminUserRow); ok {
		r0 = rf(ctx, limit, offset, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.AdminUserRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) int); ok {
		r1 = rf(ctx, limit, offset, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, limit, offset, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdminRepo_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockAdminRepo_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - search string
func (_e *MockAdminRepo_Expecter) ListUsers(ctx interface{}, limit interface{}, offset interface{}, search interface{}) *MockAdminRepo_ListUsers_Call {
	return &MockAdminRepo_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, limit, offset, search)}
}

func (_c *MockAdminRepo_ListUsers_Call) Run(run func(ctx context.Context, limit int, offset int, search string)) *MockAdminRepo_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockAdminRepo_ListUsers_Call) Return(_a0 []repository.AdminUserRow, _a1 int, _a2 error) *MockAdminRepo_ListUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdminRepo_ListUsers_Call) RunAndReturn(run func(context.Context, int, int, string) ([]repository.AdminUserRow, int, error)) *MockAdminRepo_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRepo creates a new instance of MockAdminRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepo {
	mock := &MockAdminRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
