// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPasswordResetRepo is an autogenerated mock type for the PasswordResetRepo type
type MockPasswordResetRepo struct {
	mock.Mock
}

type MockPasswordResetRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetRepo) EXPECT() *MockPasswordResetRepo_Expecter {
	return &MockPasswordResetRepo_Expecter{mock: &_m.Mock}
}

// CreatePasswordResetToken provides a mock function with given fields: ctx, token
func (_m *MockPasswordResetRepo) CreatePasswordResetToken(ctx context.Context, token *models.PasswordResetToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreatePasswordResetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PasswordResetToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetRepo_CreatePasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePasswordResetToken'
type MockPasswordResetRepo_CreatePasswordResetToken_Call struct {
	*mock.Call
}

// CreatePasswordResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.PasswordResetToken
func (_e *MockPasswordResetRepo_Expecter) CreatePasswordResetToken(ctx interface{}, token interface{}) *MockPasswordResetRepo_CreatePasswordResetToken_Call {
	return &MockPasswordResetRepo_CreatePasswordResetToken_Call{Call: _e.mock.On("CreatePasswordResetToken", ctx, token)}
}

func (_c *MockPasswordResetRepo_CreatePasswordResetToken_Call) Run(run func(ctx context.Context, token *models.PasswordResetToken)) *MockPasswordResetRepo_CreatePasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PasswordResetToken))
	})
	return _c
}

func (_c *MockPasswordResetRepo_CreatePasswordResetToken_Call) Return(_a0 error) *MockPasswordResetRepo_CreatePasswordResetToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetRepo_CreatePasswordResetToken_Call) RunAndReturn(run func(context.Context, *models.PasswordResetToken) error) *MockPasswordResetRepo_CreatePasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidPasswordResetToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockPasswordResetRepo) GetValidPasswordResetToken(ctx context.Context, tokenHash string) (*models.PasswordResetToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetValidPasswordResetToken")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PasswordResetToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PasswordResetToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetRepo_GetValidPasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidPasswordResetToken'
type MockPasswordResetRepo_GetValidPasswordResetToken_Call struct {
	*mock.Call
}

// GetValidPasswordResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockPasswordResetRepo_Expecter) GetValidPasswordResetToken(ctx interface{}, tokenHash interface{}) *MockPasswordResetRepo_GetValidPasswordResetToken_Call {
	return &MockPasswordResetRepo_GetValidPasswordResetToken_Call{Call: _e.mock.On("GetValidPasswordResetToken", ctx, tokenHash)}
}

func (_c *MockPasswordResetRepo_GetValidPasswordResetToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockPasswordResetRepo_GetValidPasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetRepo_GetValidPasswordResetToken_Call) Return(_a0 *models.PasswordResetToken, _a1 error) *MockPasswordResetRepo_GetValidPasswordResetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetRepo_GetValidPasswordResetToken_Call) RunAndReturn(run func(context.Context, string) (*models.PasswordResetToken, error)) *MockPasswordResetRepo_GetValidPasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateUserPasswordResetTokens provides a mock function with given fields: ctx, userID
func (_m *MockPasswordResetRepo) InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateUserPasswordResetTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserPasswordResetTokens'
type MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call struct {
	*mock.Call
}

// InvalidateUserPasswordResetTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPasswordResetRepo_Expecter) InvalidateUserPasswordResetTokens(ctx interface{}, userID interface{}) *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call {
	return &MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call{Call: _e.mock.On("InvalidateUserPasswordResetTokens", ctx, userID)}
}

func (_c *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call) Return(_a0 error) *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockPasswordResetRepo_InvalidateUserPasswordResetTokens_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPasswordResetTokenUsed provides a mock function with given fields: ctx, tokenID
func (_m *MockPasswordResetRepo) MarkPasswordResetTokenUsed(ctx context.Context, tokenID uuid.UUID) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPasswordResetTokenUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPasswordResetTokenUsed'
type MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call struct {
	*mock.Call
}

// MarkPasswordResetTokenUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID uuid.UUID
func (_e *MockPasswordResetRepo_Expecter) MarkPasswordResetTokenUsed(ctx interface{}, tokenID interface{}) *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call {
	return &MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call{Call: _e.mock.On("MarkPasswordResetTokenUsed", ctx, tokenID)}
}

func (_c *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call) Run(run func(ctx context.Context, tokenID uuid.UUID)) *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call) Return(_a0 error) *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockPasswordResetRepo_MarkPasswordResetTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordResetRepo creates a new instance of MockPasswordResetRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetRepo {
	mock := &MockPasswordResetRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
