// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRoleRepo is an autogenerated mock type for the RoleRepo type
type MockRoleRepo struct {
	mock.Mock
}

type MockRoleRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepo) EXPECT() *MockRoleRepo_Expecter {
	return &MockRoleRepo_Expecter{mock: &_m.Mock}
}

// LoadRolePermissions provides a mock function with given fields: ctx
func (_m *MockRoleRepo) LoadRolePermissions(ctx context.Context) (map[string][]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadRolePermissions")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string][]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string][]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepo_LoadRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRolePermissions'
type MockRoleRepo_LoadRolePermissions_Call struct {
	*mock.Call
}

// LoadRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepo_Expecter) LoadRolePermissions(ctx interface{}) *MockRoleRepo_LoadRolePermissions_Call {
	return &MockRoleRepo_LoadRolePermissions_Call{Call: _e.mock.On("LoadRolePermissions", ctx)}
}

func (_c *MockRoleRepo_LoadRolePermissions_Call) Run(run func(ctx context.Context)) *MockRoleRepo_LoadRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepo_LoadRolePermissions_Call) Return(_a0 map[string][]string, _a1 error) *MockRoleRepo_LoadRolePermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepo_LoadRolePermissions_Call) RunAndReturn(run func(context.Context) (map[string][]string, error)) *MockRoleRepo_LoadRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepo creates a new instance of MockRoleRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepo {
	mock := &MockRoleRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
