// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRequestRepo is an autogenerated mock type for the RequestRepo type.
type MockRequestRepo struct {
	mock.Mock
}

type MockRequestRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestRepo) EXPECT() *MockRequestRepo_Expecter {
	return &MockRequestRepo_Expecter{mock: &_m.Mock}
}

// CountRequestsByUserID provides a mock function with given fields: ctx, userID.
func (_m *MockRequestRepo) CountRequestsByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountRequestsByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestRepo_CountRequestsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRequestsByUserID'.
type MockRequestRepo_CountRequestsByUserID_Call struct {
	*mock.Call
}

// CountRequestsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRequestRepo_Expecter) CountRequestsByUserID(ctx interface{}, userID interface{}) *MockRequestRepo_CountRequestsByUserID_Call {
	return &MockRequestRepo_CountRequestsByUserID_Call{Call: _e.mock.On("CountRequestsByUserID", ctx, userID)}
}

func (_c *MockRequestRepo_CountRequestsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRequestRepo_CountRequestsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRequestRepo_CountRequestsByUserID_Call) Return(_a0 int, _a1 error) *MockRequestRepo_CountRequestsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestRepo_CountRequestsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockRequestRepo_CountRequestsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function with given fields: ctx, file.
func (_m *MockRequestRepo) CreateFile(ctx context.Context, file *models.File) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.File) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestRepo_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'.
type MockRequestRepo_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.File
func (_e *MockRequestRepo_Expecter) CreateFile(ctx interface{}, file interface{}) *MockRequestRepo_CreateFile_Call {
	return &MockRequestRepo_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, file)}
}

func (_c *MockRequestRepo_CreateFile_Call) Run(run func(ctx context.Context, file *models.File)) *MockRequestRepo_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.File))
	})
	return _c
}

func (_c *MockRequestRepo_CreateFile_Call) Return(_a0 error) *MockRequestRepo_CreateFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestRepo_CreateFile_Call) RunAndReturn(run func(context.Context, *models.File) error) *MockRequestRepo_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequest provides a mock function with given fields: ctx, req.
func (_m *MockRequestRepo) CreateRequest(ctx context.Context, req *models.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestRepo_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'.
type MockRequestRepo_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
func (_e *MockRequestRepo_Expecter) CreateRequest(ctx interface{}, req interface{}) *MockRequestRepo_CreateRequest_Call {
	return &MockRequestRepo_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, req)}
}

func (_c *MockRequestRepo_CreateRequest_Call) Run(run func(ctx context.Context, req *models.Request)) *MockRequestRepo_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request))
	})
	return _c
}

func (_c *MockRequestRepo_CreateRequest_Call) Return(_a0 error) *MockRequestRepo_CreateRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestRepo_CreateRequest_Call) RunAndReturn(run func(context.Context, *models.Request) error) *MockRequestRepo_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResponse provides a mock function with given fields: ctx, resp.
func (_m *MockRequestRepo) CreateResponse(ctx context.Context, resp *models.Response) error {
	ret := _m.Called(ctx, resp)

	if len(ret) == 0 {
		panic("no return value specified for CreateResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Response) error); ok {
		r0 = rf(ctx, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestRepo_CreateResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResponse'.
type MockRequestRepo_CreateResponse_Call struct {
	*mock.Call
}

// CreateResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - resp *models.Response
func (_e *MockRequestRepo_Expecter) CreateResponse(ctx interface{}, resp interface{}) *MockRequestRepo_CreateResponse_Call {
	return &MockRequestRepo_CreateResponse_Call{Call: _e.mock.On("CreateResponse", ctx, resp)}
}

func (_c *MockRequestRepo_CreateResponse_Call) Run(run func(ctx context.Context, resp *models.Response)) *MockRequestRepo_CreateResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Response))
	})
	return _c
}

func (_c *MockRequestRepo_CreateResponse_Call) Return(_a0 error) *MockRequestRepo_CreateResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestRepo_CreateResponse_Call) RunAndReturn(run func(context.Context, *models.Response) error) *MockRequestRepo_CreateResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByRequestID provides a mock function with given fields: ctx, requestID.
func (_m *MockRequestRepo) GetFilesByRequestID(ctx context.Context, requestID uuid.UUID) ([]models.File, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByRequestID")
	}

	var r0 []models.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.File, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.File); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestRepo_GetFilesByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByRequestID'.
type MockRequestRepo_GetFilesByRequestID_Call struct {
	*mock.Call
}

// GetFilesByRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockRequestRepo_Expecter) GetFilesByRequestID(ctx interface{}, requestID interface{}) *MockRequestRepo_GetFilesByRequestID_Call {
	return &MockRequestRepo_GetFilesByRequestID_Call{Call: _e.mock.On("GetFilesByRequestID", ctx, requestID)}
}

func (_c *MockRequestRepo_GetFilesByRequestID_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockRequestRepo_GetFilesByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRequestRepo_GetFilesByRequestID_Call) Return(_a0 []models.File, _a1 error) *MockRequestRepo_GetFilesByRequestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestRepo_GetFilesByRequestID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.File, error)) *MockRequestRepo_GetFilesByRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentRequestsWithResponses provides a mock function with given fields: ctx, userID, limit.
func (_m *MockRequestRepo) GetRecentRequestsWithResponses(ctx context.Context, userID uuid.UUID, limit int) ([]models.Request, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentRequestsWithResponses")
	}

	var r0 []models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]models.Request, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []models.Request); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestRepo_GetRecentRequestsWithResponses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentRequestsWithResponses'.
type MockRequestRepo_GetRecentRequestsWithResponses_Call struct {
	*mock.Call
}

// GetRecentRequestsWithResponses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
func (_e *MockRequestRepo_Expecter) GetRecentRequestsWithResponses(ctx interface{}, userID interface{}, limit interface{}) *MockRequestRepo_GetRecentRequestsWithResponses_Call {
	return &MockRequestRepo_GetRecentRequestsWithResponses_Call{Call: _e.mock.On("GetRecentRequestsWithResponses", ctx, userID, limit)}
}

func (_c *MockRequestRepo_GetRecentRequestsWithResponses_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int)) *MockRequestRepo_GetRecentRequestsWithResponses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockRequestRepo_GetRecentRequestsWithResponses_Call) Return(_a0 []models.Request, _a1 error) *MockRequestRepo_GetRecentRequestsWithResponses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestRepo_GetRecentRequestsWithResponses_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]models.Request, error)) *MockRequestRepo_GetRecentRequestsWithResponses_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestByID provides a mock function with given fields: ctx, id.
func (_m *MockRequestRepo) GetRequestByID(ctx context.Context, id uuid.UUID) (*models.Request, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestByID")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Request, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestRepo_GetRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestByID'.
type MockRequestRepo_GetRequestByID_Call struct {
	*mock.Call
}

// GetRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRequestRepo_Expecter) GetRequestByID(ctx interface{}, id interface{}) *MockRequestRepo_GetRequestByID_Call {
	return &MockRequestRepo_GetRequestByID_Call{Call: _e.mock.On("GetRequestByID", ctx, id)}
}

func (_c *MockRequestRepo_GetRequestByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRequestRepo_GetRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRequestRepo_GetRequestByID_Call) Return(_a0 *models.Request, _a1 error) *MockRequestRepo_GetRequestByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestRepo_GetRequestByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Request, error)) *MockRequestRepo_GetRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestsByUserID provides a mock function with given fields: ctx, userID, limit, offset.
func (_m *MockRequestRepo) GetRequestsByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]models.Request, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestsByUserID")
	}

	var r0 []models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]models.Request, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []models.Request); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestRepo_GetRequestsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestsByUserID'.
type MockRequestRepo_GetRequestsByUserID_Call struct {
	*mock.Call
}

// GetRequestsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockRequestRepo_Expecter) GetRequestsByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockRequestRepo_GetRequestsByUserID_Call {
	return &MockRequestRepo_GetRequestsByUserID_Call{Call: _e.mock.On("GetRequestsByUserID", ctx, userID, limit, offset)}
}

func (_c *MockRequestRepo_GetRequestsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockRequestRepo_GetRequestsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRequestRepo_GetRequestsByUserID_Call) Return(_a0 []models.Request, _a1 error) *MockRequestRepo_GetRequestsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestRepo_GetRequestsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]models.Request, error)) *MockRequestRepo_GetRequestsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetResponseByRequestID provides a mock function with given fields: ctx, requestID.
func (_m *MockRequestRepo) GetResponseByRequestID(ctx context.Context, requestID uuid.UUID) (*models.Response, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetResponseByRequestID")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Response, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Response); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestRepo_GetResponseByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResponseByRequestID'.
type MockRequestRepo_GetResponseByRequestID_Call struct {
	*mock.Call
}

// GetResponseByRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockRequestRepo_Expecter) GetResponseByRequestID(ctx interface{}, requestID interface{}) *MockRequestRepo_GetResponseByRequestID_Call {
	return &MockRequestRepo_GetResponseByRequestID_Call{Call: _e.mock.On("GetResponseByRequestID", ctx, requestID)}
}

func (_c *MockRequestRepo_GetResponseByRequestID_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockRequestRepo_GetResponseByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRequestRepo_GetResponseByRequestID_Call) Return(_a0 *models.Response, _a1 error) *MockRequestRepo_GetResponseByRequestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestRepo_GetResponseByRequestID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Response, error)) *MockRequestRepo_GetResponseByRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequestStatus provides a mock function with given fields: ctx, requestID, status.
func (_m *MockRequestRepo) UpdateRequestStatus(ctx context.Context, requestID uuid.UUID, status string) error {
	ret := _m.Called(ctx, requestID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, requestID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestRepo_UpdateRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequestStatus'.
type MockRequestRepo_UpdateRequestStatus_Call struct {
	*mock.Call
}

// UpdateRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - status string
func (_e *MockRequestRepo_Expecter) UpdateRequestStatus(ctx interface{}, requestID interface{}, status interface{}) *MockRequestRepo_UpdateRequestStatus_Call {
	return &MockRequestRepo_UpdateRequestStatus_Call{Call: _e.mock.On("UpdateRequestStatus", ctx, requestID, status)}
}

func (_c *MockRequestRepo_UpdateRequestStatus_Call) Run(run func(ctx context.Context, requestID uuid.UUID, status string)) *MockRequestRepo_UpdateRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRequestRepo_UpdateRequestStatus_Call) Return(_a0 error) *MockRequestRepo_UpdateRequestStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestRepo_UpdateRequestStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRequestRepo_UpdateRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestRepo creates a new instance of MockRequestRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestRepo {
	mock := &MockRequestRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
