// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fedutinova/smartheart/back-api/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockECGChatRepo is an autogenerated mock type for the ECGChatRepo type
type MockECGChatRepo struct {
	mock.Mock
}

type MockECGChatRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockECGChatRepo) EXPECT() *MockECGChatRepo_Expecter {
	return &MockECGChatRepo_Expecter{mock: &_m.Mock}
}

// CreateECGChatMessage provides a mock function with given fields: ctx, msg
func (_m *MockECGChatRepo) CreateECGChatMessage(ctx context.Context, msg *models.ECGChatMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateECGChatMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ECGChatMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockECGChatRepo_CreateECGChatMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateECGChatMessage'
type MockECGChatRepo_CreateECGChatMessage_Call struct {
	*mock.Call
}

// CreateECGChatMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *models.ECGChatMessage
func (_e *MockECGChatRepo_Expecter) CreateECGChatMessage(ctx interface{}, msg interface{}) *MockECGChatRepo_CreateECGChatMessage_Call {
	return &MockECGChatRepo_CreateECGChatMessage_Call{Call: _e.mock.On("CreateECGChatMessage", ctx, msg)}
}

func (_c *MockECGChatRepo_CreateECGChatMessage_Call) Run(run func(ctx context.Context, msg *models.ECGChatMessage)) *MockECGChatRepo_CreateECGChatMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ECGChatMessage))
	})
	return _c
}

func (_c *MockECGChatRepo_CreateECGChatMessage_Call) Return(_a0 error) *MockECGChatRepo_CreateECGChatMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockECGChatRepo_CreateECGChatMessage_Call) RunAndReturn(run func(context.Context, *models.ECGChatMessage) error) *MockECGChatRepo_CreateECGChatMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetECGChatMessages provides a mock function with given fields: ctx, requestID, userID
func (_m *MockECGChatRepo) GetECGChatMessages(ctx context.Context, requestID uuid.UUID, userID uuid.UUID) ([]models.ECGChatMessage, error) {
	ret := _m.Called(ctx, requestID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetECGChatMessages")
	}

	var r0 []models.ECGChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.ECGChatMessage, error)); ok {
		return rf(ctx, requestID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.ECGChatMessage); ok {
		r0 = rf(ctx, requestID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ECGChatMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockECGChatRepo_GetECGChatMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetECGChatMessages'
type MockECGChatRepo_GetECGChatMessages_Call struct {
	*mock.Call
}

// GetECGChatMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - userID uuid.UUID
func (_e *MockECGChatRepo_Expecter) GetECGChatMessages(ctx interface{}, requestID interface{}, userID interface{}) *MockECGChatRepo_GetECGChatMessages_Call {
	return &MockECGChatRepo_GetECGChatMessages_Call{Call: _e.mock.On("GetECGChatMessages", ctx, requestID, userID)}
}

func (_c *MockECGChatRepo_GetECGChatMessages_Call) Run(run func(ctx context.Context, requestID uuid.UUID, userID uuid.UUID)) *MockECGChatRepo_GetECGChatMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockECGChatRepo_GetECGChatMessages_Call) Return(_a0 []models.ECGChatMessage, _a1 error) *MockECGChatRepo_GetECGChatMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockECGChatRepo_GetECGChatMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.ECGChatMessage, error)) *MockECGChatRepo_GetECGChatMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockECGChatRepo creates a new instance of MockECGChatRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockECGChatRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockECGChatRepo {
	mock := &MockECGChatRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
