package models

// ECGRhythmResult is the rhythm-classification block produced by cv_service
// and embedded into ECGResponseContent alongside the existing measurement
// result. Nil when CV inference was unavailable or failed.
//
// Top3 and BinaryFlags are persisted (handy for analytics and re-rendering),
// but the current frontend does not show them — the conclusion surface is
// Explanation, generated by a vision LLM on top of the CV result.
type ECGRhythmResult struct {
	PredCode       string                `json:"pred_code"`
	PredLabelRU    string                `json:"pred_label_ru"`
	LayoutLabel    string                `json:"layout_label"`
	PreprocessName string                `json:"preprocess_name"`
	Top3           []RhythmClassProb     `json:"top3"`
	BinaryFlags    []RhythmBinaryFlag    `json:"binary_flags"`
	Explanation    *ECGRhythmExplanation `json:"explanation,omitempty"`
}

// ECGRhythmExplanation is the four-field narrative the vision LLM produces on
// top of the CV rhythm prediction. Field names match what the original
// ecg_site_delivery_bundle llm_service.py prompt emitted, so the JSON shape is
// stable across the (Python) reference implementation and our Go port.
type ECGRhythmExplanation struct {
	PredictionLine  string `json:"prediction_line"`
	DescriptionText string `json:"description_text"`
	ConclusionText  string `json:"conclusion_text"`
	NoteText        string `json:"note_text"`
}

// RhythmClassProb is one entry of the top-K rhythm prediction list.
type RhythmClassProb struct {
	Code    string  `json:"code"`
	LabelRU string  `json:"label_ru"`
	Prob    float64 `json:"prob"`
}

// RhythmBinaryFlag is one auxiliary binary indicator (e.g. ST-T abnormalities).
// cv_service emits flags above its internal probability threshold only.
type RhythmBinaryFlag struct {
	Code    string  `json:"code"`
	LabelRU string  `json:"label_ru"`
	Prob    float64 `json:"prob"`
}
