// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenBlacklistChecker is an autogenerated mock type for the TokenBlacklistChecker type
type MockTokenBlacklistChecker struct {
	mock.Mock
}

type MockTokenBlacklistChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenBlacklistChecker) EXPECT() *MockTokenBlacklistChecker_Expecter {
	return &MockTokenBlacklistChecker_Expecter{mock: &_m.Mock}
}

// IsTokenBlacklisted provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenBlacklistChecker) IsTokenBlacklisted(ctx context.Context, tokenHash string) (bool, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenBlacklistChecker_IsTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenBlacklisted'
type MockTokenBlacklistChecker_IsTokenBlacklisted_Call struct {
	*mock.Call
}

// IsTokenBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenBlacklistChecker_Expecter) IsTokenBlacklisted(ctx interface{}, tokenHash interface{}) *MockTokenBlacklistChecker_IsTokenBlacklisted_Call {
	return &MockTokenBlacklistChecker_IsTokenBlacklisted_Call{Call: _e.mock.On("IsTokenBlacklisted", ctx, tokenHash)}
}

func (_c *MockTokenBlacklistChecker_IsTokenBlacklisted_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenBlacklistChecker_IsTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenBlacklistChecker_IsTokenBlacklisted_Call) Return(_a0 bool, _a1 error) *MockTokenBlacklistChecker_IsTokenBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenBlacklistChecker_IsTokenBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenBlacklistChecker_IsTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenBlacklistChecker creates a new instance of MockTokenBlacklistChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenBlacklistChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenBlacklistChecker {
	mock := &MockTokenBlacklistChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
