// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

type MockSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionService) EXPECT() *MockSessionService_Expecter {
	return &MockSessionService_Expecter{mock: &_m.Mock}
}

// GetLoginAttempts provides a mock function with given fields: ctx, email
func (_m *MockSessionService) GetLoginAttempts(ctx context.Context, email string) (int64, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetLoginAttempts")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_GetLoginAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoginAttempts'
type MockSessionService_GetLoginAttempts_Call struct {
	*mock.Call
}

// GetLoginAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockSessionService_Expecter) GetLoginAttempts(ctx interface{}, email interface{}) *MockSessionService_GetLoginAttempts_Call {
	return &MockSessionService_GetLoginAttempts_Call{Call: _e.mock.On("GetLoginAttempts", ctx, email)}
}

func (_c *MockSessionService_GetLoginAttempts_Call) Run(run func(ctx context.Context, email string)) *MockSessionService_GetLoginAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionService_GetLoginAttempts_Call) Return(_a0 int64, _a1 error) *MockSessionService_GetLoginAttempts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionService_GetLoginAttempts_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockSessionService_GetLoginAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenUserID provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionService) GetRefreshTokenUserID(ctx context.Context, tokenHash string) (string, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_GetRefreshTokenUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenUserID'
type MockSessionService_GetRefreshTokenUserID_Call struct {
	*mock.Call
}

// GetRefreshTokenUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionService_Expecter) GetRefreshTokenUserID(ctx interface{}, tokenHash interface{}) *MockSessionService_GetRefreshTokenUserID_Call {
	return &MockSessionService_GetRefreshTokenUserID_Call{Call: _e.mock.On("GetRefreshTokenUserID", ctx, tokenHash)}
}

func (_c *MockSessionService_GetRefreshTokenUserID_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionService_GetRefreshTokenUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionService_GetRefreshTokenUserID_Call) Return(_a0 string, _a1 error) *MockSessionService_GetRefreshTokenUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionService_GetRefreshTokenUserID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockSessionService_GetRefreshTokenUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrLoginAttempts provides a mock function with given fields: ctx, email, window
func (_m *MockSessionService) IncrLoginAttempts(ctx context.Context, email string, window time.Duration) (int64, error) {
	ret := _m.Called(ctx, email, window)

	if len(ret) == 0 {
		panic("no return value specified for IncrLoginAttempts")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (int64, error)); ok {
		return rf(ctx, email, window)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) int64); ok {
		r0 = rf(ctx, email, window)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, email, window)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_IncrLoginAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrLoginAttempts'
type MockSessionService_IncrLoginAttempts_Call struct {
	*mock.Call
}

// IncrLoginAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - window time.Duration
func (_e *MockSessionService_Expecter) IncrLoginAttempts(ctx interface{}, email interface{}, window interface{}) *MockSessionService_IncrLoginAttempts_Call {
	return &MockSessionService_IncrLoginAttempts_Call{Call: _e.mock.On("IncrLoginAttempts", ctx, email, window)}
}

func (_c *MockSessionService_IncrLoginAttempts_Call) Run(run func(ctx context.Context, email string, window time.Duration)) *MockSessionService_IncrLoginAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionService_IncrLoginAttempts_Call) Return(_a0 int64, _a1 error) *MockSessionService_IncrLoginAttempts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionService_IncrLoginAttempts_Call) RunAndReturn(run func(context.Context, string, time.Duration) (int64, error)) *MockSessionService_IncrLoginAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenBlacklisted provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionService) IsTokenBlacklisted(ctx context.Context, tokenHash string) (bool, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_IsTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenBlacklisted'
type MockSessionService_IsTokenBlacklisted_Call struct {
	*mock.Call
}

// IsTokenBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionService_Expecter) IsTokenBlacklisted(ctx interface{}, tokenHash interface{}) *MockSessionService_IsTokenBlacklisted_Call {
	return &MockSessionService_IsTokenBlacklisted_Call{Call: _e.mock.On("IsTokenBlacklisted", ctx, tokenHash)}
}

func (_c *MockSessionService_IsTokenBlacklisted_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionService_IsTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionService_IsTokenBlacklisted_Call) Return(_a0 bool, _a1 error) *MockSessionService_IsTokenBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionService_IsTokenBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockSessionService_IsTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockSessionService) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSessionService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionService_Expecter) Ping(ctx interface{}) *MockSessionService_Ping_Call {
	return &MockSessionService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockSessionService_Ping_Call) Run(run func(ctx context.Context)) *MockSessionService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionService_Ping_Call) Return(_a0 error) *MockSessionService_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionService_Ping_Call) RunAndReturn(run func(context.Context) error) *MockSessionService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ResetLoginAttempts provides a mock function with given fields: ctx, email
func (_m *MockSessionService) ResetLoginAttempts(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResetLoginAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionService_ResetLoginAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetLoginAttempts'
type MockSessionService_ResetLoginAttempts_Call struct {
	*mock.Call
}

// ResetLoginAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockSessionService_Expecter) ResetLoginAttempts(ctx interface{}, email interface{}) *MockSessionService_ResetLoginAttempts_Call {
	return &MockSessionService_ResetLoginAttempts_Call{Call: _e.mock.On("ResetLoginAttempts", ctx, email)}
}

func (_c *MockSessionService_ResetLoginAttempts_Call) Run(run func(ctx context.Context, email string)) *MockSessionService_ResetLoginAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionService_ResetLoginAttempts_Call) Return(_a0 error) *MockSessionService_ResetLoginAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionService_ResetLoginAttempts_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionService_ResetLoginAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserTokens provides a mock function with given fields: ctx, userID
func (_m *MockSessionService) RevokeAllUserTokens(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionService_RevokeAllUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserTokens'
type MockSessionService_RevokeAllUserTokens_Call struct {
	*mock.Call
}

// RevokeAllUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionService_Expecter) RevokeAllUserTokens(ctx interface{}, userID interface{}) *MockSessionService_RevokeAllUserTokens_Call {
	return &MockSessionService_RevokeAllUserTokens_Call{Call: _e.mock.On("RevokeAllUserTokens", ctx, userID)}
}

func (_c *MockSessionService_RevokeAllUserTokens_Call) Run(run func(ctx context.Context, userID string)) *MockSessionService_RevokeAllUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionService_RevokeAllUserTokens_Call) Return(_a0 error) *MockSessionService_RevokeAllUserTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionService_RevokeAllUserTokens_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionService_RevokeAllUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionService) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionService_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockSessionService_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionService_Expecter) RevokeRefreshToken(ctx interface{}, tokenHash interface{}) *MockSessionService_RevokeRefreshToken_Call {
	return &MockSessionService_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenHash)}
}

func (_c *MockSessionService_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionService_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionService_RevokeRefreshToken_Call) Return(_a0 error) *MockSessionService_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionService_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionService_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreBlacklistedToken provides a mock function with given fields: ctx, tokenHash, ttl
func (_m *MockSessionService) StoreBlacklistedToken(ctx context.Context, tokenHash string, ttl time.Duration) error {
	ret := _m.Called(ctx, tokenHash, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreBlacklistedToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, tokenHash, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionService_StoreBlacklistedToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreBlacklistedToken'
type MockSessionService_StoreBlacklistedToken_Call struct {
	*mock.Call
}

// StoreBlacklistedToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - ttl time.Duration
func (_e *MockSessionService_Expecter) StoreBlacklistedToken(ctx interface{}, tokenHash interface{}, ttl interface{}) *MockSessionService_StoreBlacklistedToken_Call {
	return &MockSessionService_StoreBlacklistedToken_Call{Call: _e.mock.On("StoreBlacklistedToken", ctx, tokenHash, ttl)}
}

func (_c *MockSessionService_StoreBlacklistedToken_Call) Run(run func(ctx context.Context, tokenHash string, ttl time.Duration)) *MockSessionService_StoreBlacklistedToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionService_StoreBlacklistedToken_Call) Return(_a0 error) *MockSessionService_StoreBlacklistedToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionService_StoreBlacklistedToken_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockSessionService_StoreBlacklistedToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function with given fields: ctx, userID, tokenHash, ttl
func (_m *MockSessionService) StoreRefreshToken(ctx context.Context, userID string, tokenHash string, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, tokenHash, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, tokenHash, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionService_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockSessionService_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenHash string
//   - ttl time.Duration
func (_e *MockSessionService_Expecter) StoreRefreshToken(ctx interface{}, userID interface{}, tokenHash interface{}, ttl interface{}) *MockSessionService_StoreRefreshToken_Call {
	return &MockSessionService_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, userID, tokenHash, ttl)}
}

func (_c *MockSessionService_StoreRefreshToken_Call) Run(run func(ctx context.Context, userID string, tokenHash string, ttl time.Duration)) *MockSessionService_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockSessionService_StoreRefreshToken_Call) Return(_a0 error) *MockSessionService_StoreRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionService_StoreRefreshToken_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockSessionService_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
