// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/fedutinova/smartheart/back-api/storage"

	time "time"
)

// MockStorage is an autogenerated mock type for the Storage type.
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, key.
func (_m *MockStorage) DeleteFile(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'.
type MockStorage_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorage_Expecter) DeleteFile(ctx interface{}, key interface{}) *MockStorage_DeleteFile_Call {
	return &MockStorage_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, key)}
}

func (_c *MockStorage_DeleteFile_Call) Run(run func(ctx context.Context, key string)) *MockStorage_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteFile_Call) Return(_a0 error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function with given fields: ctx, key.
func (_m *MockStorage) GetFile(ctx context.Context, key string) (io.ReadCloser, string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStorage_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'.
type MockStorage_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorage_Expecter) GetFile(ctx interface{}, key interface{}) *MockStorage_GetFile_Call {
	return &MockStorage_GetFile_Call{Call: _e.mock.On("GetFile", ctx, key)}
}

func (_c *MockStorage_GetFile_Call) Run(run func(ctx context.Context, key string)) *MockStorage_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetFile_Call) Return(_a0 io.ReadCloser, _a1 string, _a2 error) *MockStorage_GetFile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStorage_GetFile_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, string, error)) *MockStorage_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function with given fields: ctx, key, expiration.
func (_m *MockStorage) GetPresignedURL(ctx context.Context, key string, expiration time.Duration) (string, error) {
	ret := _m.Called(ctx, key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, expiration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, expiration)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, expiration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'.
type MockStorage_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiration time.Duration
func (_e *MockStorage_Expecter) GetPresignedURL(ctx interface{}, key interface{}, expiration interface{}) *MockStorage_GetPresignedURL_Call {
	return &MockStorage_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, key, expiration)}
}

func (_c *MockStorage_GetPresignedURL_Call) Run(run func(ctx context.Context, key string, expiration time.Duration)) *MockStorage_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockStorage_GetPresignedURL_Call) Return(_a0 string, _a1 error) *MockStorage_GetPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetPresignedURL_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockStorage_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: ctx, filename, content, contentType.
func (_m *MockStorage) UploadFile(ctx context.Context, filename string, content io.Reader, contentType string) (*storage.UploadResult, error) {
	ret := _m.Called(ctx, filename, content, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 *storage.UploadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) (*storage.UploadResult, error)); ok {
		return rf(ctx, filename, content, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) *storage.UploadResult); ok {
		r0 = rf(ctx, filename, content, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.UploadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, string) error); ok {
		r1 = rf(ctx, filename, content, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'.
type MockStorage_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
//   - content io.Reader
//   - contentType string
func (_e *MockStorage_Expecter) UploadFile(ctx interface{}, filename interface{}, content interface{}, contentType interface{}) *MockStorage_UploadFile_Call {
	return &MockStorage_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, filename, content, contentType)}
}

func (_c *MockStorage_UploadFile_Call) Run(run func(ctx context.Context, filename string, content io.Reader, contentType string)) *MockStorage_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(string))
	})
	return _c
}

func (_c *MockStorage_UploadFile_Call) Return(_a0 *storage.UploadResult, _a1 error) *MockStorage_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UploadFile_Call) RunAndReturn(run func(context.Context, string, io.Reader, string) (*storage.UploadResult, error)) *MockStorage_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
