// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	job "github.com/fedutinova/smartheart/back-api/job"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockQueue) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockQueue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Close() *MockQueue_Close_Call {
	return &MockQueue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockQueue_Close_Call) Run(run func()) *MockQueue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Close_Call) Return(_a0 error) *MockQueue_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Close_Call) RunAndReturn(run func() error) *MockQueue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function with given fields: ctx, j
func (_m *MockQueue) Enqueue(ctx context.Context, j *job.Job) (uuid.UUID, error) {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *job.Job) (uuid.UUID, error)); ok {
		return rf(ctx, j)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *job.Job) uuid.UUID); ok {
		r0 = rf(ctx, j)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *job.Job) error); ok {
		r1 = rf(ctx, j)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - j *job.Job
func (_e *MockQueue_Expecter) Enqueue(ctx interface{}, j interface{}) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, j)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(ctx context.Context, j *job.Job)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*job.Job))
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(_a0 uuid.UUID, _a1 error) *MockQueue_Enqueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(context.Context, *job.Job) (uuid.UUID, error)) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *MockQueue) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockQueue_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockQueue_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Len() *MockQueue_Len_Call {
	return &MockQueue_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockQueue_Len_Call) Run(run func()) *MockQueue_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Len_Call) Return(_a0 int) *MockQueue_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Len_Call) RunAndReturn(run func() int) *MockQueue_Len_Call {
	_c.Call.Return(run)
	return _c
}

// StartConsumers provides a mock function with given fields: ctx, n, handler
func (_m *MockQueue) StartConsumers(ctx context.Context, n int, handler job.Handler) {
	_m.Called(ctx, n, handler)
}

// MockQueue_StartConsumers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartConsumers'
type MockQueue_StartConsumers_Call struct {
	*mock.Call
}

// StartConsumers is a helper method to define mock.On call
//   - ctx context.Context
//   - n int
//   - handler job.Handler
func (_e *MockQueue_Expecter) StartConsumers(ctx interface{}, n interface{}, handler interface{}) *MockQueue_StartConsumers_Call {
	return &MockQueue_StartConsumers_Call{Call: _e.mock.On("StartConsumers", ctx, n, handler)}
}

func (_c *MockQueue_StartConsumers_Call) Run(run func(ctx context.Context, n int, handler job.Handler)) *MockQueue_StartConsumers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(job.Handler))
	})
	return _c
}

func (_c *MockQueue_StartConsumers_Call) Return() *MockQueue_StartConsumers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueue_StartConsumers_Call) RunAndReturn(run func(context.Context, int, job.Handler)) *MockQueue_StartConsumers_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function with given fields: ctx, id
func (_m *MockQueue) Status(ctx context.Context, id uuid.UUID) (*job.Job, bool) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *job.Job
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*job.Job, bool)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *job.Job); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockQueue_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockQueue_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQueue_Expecter) Status(ctx interface{}, id interface{}) *MockQueue_Status_Call {
	return &MockQueue_Status_Call{Call: _e.mock.On("Status", ctx, id)}
}

func (_c *MockQueue_Status_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQueue_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQueue_Status_Call) Return(_a0 *job.Job, _a1 bool) *MockQueue_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_Status_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*job.Job, bool)) *MockQueue_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
