// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	job "github.com/fedutinova/smartheart/back-api/job"
	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, j
func (_m *MockHandler) Execute(ctx context.Context, j *job.Job) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *job.Job) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - j *job.Job
func (_e *MockHandler_Expecter) Execute(ctx interface{}, j interface{}) *MockHandler_Execute_Call {
	return &MockHandler_Execute_Call{Call: _e.mock.On("Execute", ctx, j)}
}

func (_c *MockHandler_Execute_Call) Run(run func(ctx context.Context, j *job.Job)) *MockHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*job.Job))
	})
	return _c
}

func (_c *MockHandler_Execute_Call) Return(_a0 error) *MockHandler_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Execute_Call) RunAndReturn(run func(context.Context, *job.Job) error) *MockHandler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
